test_case("churiw", "chửi").
test_case("chuwir", "chửi").
test_case("chuwri", "chửi").
test_case("churwi", "chửi").
test_case("chuiwr", "chửi").
test_case("chuirw", "chửi").
test_case("bosp", "bóp").
test_case("bops", "bóp").
test_case("bojp", "bọp").
test_case("bopj", "bọp").
test_case("bocos", "bốc").
test_case("bosoc", "bốc").
test_case("boocs", "bốc").
test_case("bosco", "bốc").
test_case("boosc", "bốc").
test_case("bocso", "bốc").
test_case("boocj", "bộc").
test_case("bocjo", "bộc").
test_case("bojoc", "bộc").
test_case("bojco", "bộc").
test_case("boojc", "bộc").
test_case("bocoj", "bộc").
test_case("khuaang", "khuâng").
test_case("khuanga", "khuâng").
test_case("khuanag", "khuâng").
test_case("bieeng", "biêng").
test_case("bieneg", "biêng").
test_case("bienge", "biêng").
test_case("biensge", "biếng").
test_case("bienseg", "biếng").
test_case("biesneg", "biếng").
test_case("bienges", "biếng").
test_case("bienegs", "biếng").
test_case("bienesg", "biếng").
test_case("bieseng", "biếng").
test_case("biesnge", "biếng").
test_case("bieengs", "biếng").
test_case("bieensg", "biếng").
test_case("bieesng", "biếng").
test_case("biengse", "biếng").
test_case("chienefg", "chiềng").
test_case("chieefng", "chiềng").
test_case("chiefneg", "chiềng").
test_case("chieengf", "chiềng").
test_case("chiefeng", "chiềng").
test_case("chienfge", "chiềng").
test_case("chiefnge", "chiềng").
test_case("chienegf", "chiềng").
test_case("chieenfg", "chiềng").
test_case("chienfeg", "chiềng").
test_case("chiengfe", "chiềng").
test_case("chiengef", "chiềng").
test_case("khienxge", "khiễng").
test_case("khiexneg", "khiễng").
test_case("khieexng", "khiễng").
test_case("khieenxg", "khiễng").
test_case("khiengxe", "khiễng").
test_case("khienexg", "khiễng").
test_case("khiexeng", "khiễng").
test_case("khienxeg", "khiễng").
test_case("khienegx", "khiễng").
test_case("khiengex", "khiễng").
test_case("khiexnge", "khiễng").
test_case("khieengx", "khiễng").
test_case("kienegr", "kiểng").
test_case("kienrge", "kiểng").
test_case("kienreg", "kiểng").
test_case("kieenrg", "kiểng").
test_case("kiereng", "kiểng").
test_case("kieerng", "kiểng").
test_case("kierneg", "kiểng").
test_case("kiernge", "kiểng").
test_case("kiengre", "kiểng").
test_case("kieengr", "kiểng").
test_case("kienerg", "kiểng").
test_case("kienger", "kiểng").
test_case("lienejg", "liệng").
test_case("liengej", "liệng").
test_case("lieenjg", "liệng").
test_case("lienegj", "liệng").
test_case("liejeng", "liệng").
test_case("liejneg", "liệng").
test_case("lienjge", "liệng").
test_case("lieejng", "liệng").
test_case("liejnge", "liệng").
test_case("lieengj", "liệng").
test_case("lienjeg", "liệng").
test_case("liengje", "liệng").
test_case("duyetje", "duyệt").
test_case("duyeejt", "duyệt").
test_case("duyeetj", "duyệt").
test_case("duyetej", "duyệt").
test_case("duyejet", "duyệt").
test_case("duyejte", "duyệt").
test_case("huyeste", "huyết").
test_case("huyetse", "huyết").
test_case("huyeset", "huyết").
test_case("huyetes", "huyết").
test_case("huyeets", "huyết").
test_case("huyeest", "huyết").
test_case("banwg", "băng").
test_case("bangw", "băng").
test_case("bawng", "băng").
test_case("bangws", "bắng").
test_case("bawsng", "bắng").
test_case("bawngs", "bắng").
test_case("banswg", "bắng").
test_case("banwsg", "bắng").
test_case("basngw", "bắng").
test_case("bangsw", "bắng").
test_case("baswng", "bắng").
test_case("basnwg", "bắng").
test_case("bansgw", "bắng").
test_case("banwgs", "bắng").
test_case("bawnsg", "bắng").
test_case("bangwf", "bằng").
test_case("bafwng", "bằng").
test_case("bafngw", "bằng").
test_case("banfgw", "bằng").
test_case("bangfw", "bằng").
test_case("banwfg", "bằng").
test_case("bawngf", "bằng").
test_case("banwgf", "bằng").
test_case("banfwg", "bằng").
test_case("bawnfg", "bằng").
test_case("bafnwg", "bằng").
test_case("bawfng", "bằng").
test_case("banxgw", "bẵng").
test_case("banwgx", "bẵng").
test_case("bangxw", "bẵng").
test_case("bawnxg", "bẵng").
test_case("baxngw", "bẵng").
test_case("baxwng", "bẵng").
test_case("bawngx", "bẵng").
test_case("baxnwg", "bẵng").
test_case("banxwg", "bẵng").
test_case("bawxng", "bẵng").
test_case("banwxg", "bẵng").
test_case("bangwx", "bẵng").
test_case("bajnwg", "bặng").
test_case("bawnjg", "bặng").
test_case("bangwj", "bặng").
test_case("banwgj", "bặng").
test_case("banjwg", "bặng").
test_case("bajwng", "bặng").
test_case("banwjg", "bặng").
test_case("bajngw", "bặng").
test_case("banjgw", "bặng").
test_case("bangjw", "bặng").
test_case("bawjng", "bặng").
test_case("bawngj", "bặng").
test_case("chawngr", "chẳng").
test_case("changwr", "chẳng").
test_case("chanwrg", "chẳng").
test_case("charngw", "chẳng").
test_case("chawrng", "chẳng").
test_case("chanrgw", "chẳng").
test_case("changrw", "chẳng").
test_case("charwng", "chẳng").
test_case("charnwg", "chẳng").
test_case("chanwgr", "chẳng").
test_case("chanrwg", "chẳng").
test_case("chawnrg", "chẳng").
test_case("benf", "bèn").
test_case("befn", "bèn").
test_case("besn", "bén").
test_case("bens", "bén").
test_case("bejn", "bẹn").
test_case("benj", "bẹn").
test_case("benx", "bẽn").
test_case("bexn", "bẽn").
test_case("chenr", "chẻn").
test_case("chern", "chẻn").
test_case("dden", "đen").
test_case("dedn", "đen").
test_case("dend", "đen").
test_case("buf", "bù").
test_case("bus", "bú").
test_case("buj", "bụ").
test_case("bur", "bủ").
test_case("cux", "cũ").
test_case("dud", "đu").
test_case("ddu", "đu").
test_case("hoawng", "hoăng").
test_case("hoanwg", "hoăng").
test_case("hoangw", "hoăng").
test_case("hoawnxg", "hoẵng").
test_case("hoaxwng", "hoẵng").
test_case("hoaxnwg", "hoẵng").
test_case("hoawngx", "hoẵng").
test_case("hoanwxg", "hoẵng").
test_case("hoanxgw", "hoẵng").
test_case("hoawxng", "hoẵng").
test_case("hoanwgx", "hoẵng").
test_case("hoanxwg", "hoẵng").
test_case("hoangwx", "hoẵng").
test_case("hoaxngw", "hoẵng").
test_case("hoangxw", "hoẵng").
test_case("khoasnwg", "khoắng").
test_case("khoangsw", "khoắng").
test_case("khoawngs", "khoắng").
test_case("khoasngw", "khoắng").
test_case("khoangws", "khoắng").
test_case("khoanswg", "khoắng").
test_case("khoansgw", "khoắng").
test_case("khoanwsg", "khoắng").
test_case("khoawnsg", "khoắng").
test_case("khoawsng", "khoắng").
test_case("khoaswng", "khoắng").
test_case("khoanwgs", "khoắng").
test_case("loafngw", "loằng").
test_case("loanwgf", "loằng").
test_case("loawfng", "loằng").
test_case("loanwfg", "loằng").
test_case("loawnfg", "loằng").
test_case("loangwf", "loằng").
test_case("loangfw", "loằng").
test_case("loanfgw", "loằng").
test_case("loafwng", "loằng").
test_case("loanfwg", "loằng").
test_case("loawngf", "loằng").
test_case("loafnwg", "loằng").
test_case("oawrng", "oẳng").
test_case("oarwng", "oẳng").
test_case("oanwrg", "oẳng").
test_case("oanrwg", "oẳng").
test_case("oanrgw", "oẳng").
test_case("oangrw", "oẳng").
test_case("oarnwg", "oẳng").
test_case("oawnrg", "oẳng").
test_case("oanwgr", "oẳng").
test_case("oarngw", "oẳng").
test_case("oawngr", "oẳng").
test_case("oangwr", "oẳng").
test_case("buoscw", "bước").
% test_case("buwocws", "bước").
% test_case("buwocsw", "bước").
test_case("buoswc", "bước").
test_case("buowsc", "bước").
% test_case("buwoswc", "bước").
% test_case("buwowcs", "bước").
test_case("buocws", "bước").
% test_case("buwowsc", "bước").
test_case("buocsw", "bước").
test_case("buowcs", "bước").
% test_case("buwoscw", "bước").
% test_case("chuwojcw", "chược").
test_case("chuowjc", "chược").
% test_case("chuwojwc", "chược").
test_case("chuowcj", "chược").
test_case("chuojwc", "chược").
test_case("chuocwj", "chược").
% test_case("chuwowcj", "chược").
% test_case("chuwowjc", "chược").
test_case("chuojcw", "chược").
% test_case("chuwocwj", "chược").
% test_case("chuwocjw", "chược").
test_case("chuocjw", "chược").
test_case("yesme", "yếm").
test_case("yeesm", "yếm").
test_case("yemse", "yếm").
test_case("yemes", "yếm").
test_case("yesem", "yếm").
test_case("yeems", "yếm").
test_case("yeerm", "yểm").
test_case("yerme", "yểm").
test_case("yemre", "yểm").
test_case("yerem", "yểm").
test_case("yeemr", "yểm").
test_case("yemer", "yểm").
test_case("khuaya", "khuây").
test_case("khuaay", "khuây").
test_case("khuaasy", "khuấy").
test_case("khuasya", "khuấy").
test_case("khuaysa", "khuấy").
test_case("khuasay", "khuấy").
test_case("khuaays", "khuấy").
test_case("khuayas", "khuấy").
test_case("nguaayr", "nguẩy").
test_case("nguaary", "nguẩy").
test_case("nguarya", "nguẩy").
test_case("nguayar", "nguẩy").
test_case("nguaray", "nguẩy").
test_case("nguayra", "nguẩy").
test_case("bimf", "bìm").
test_case("bifm", "bìm").
test_case("bims", "bím").
test_case("bism", "bím").
test_case("birm", "bỉm").
test_case("bimr", "bỉm").
test_case("himx", "hĩm").
test_case("hixm", "hĩm").
test_case("limj", "lịm").
test_case("lijm", "lịm").
test_case("quyeen", "quyên").
test_case("quyene", "quyên").
test_case("quyesen", "quyến").
test_case("quyenes", "quyến").
test_case("quyeesn", "quyến").
test_case("quyense", "quyến").
test_case("quyesne", "quyến").
test_case("quyeens", "quyến").
test_case("quyenfe", "quyền").
test_case("quyenef", "quyền").
test_case("quyefne", "quyền").
test_case("quyefen", "quyền").
test_case("quyeefn", "quyền").
test_case("quyeenf", "quyền").
test_case("quyeren", "quyển").
test_case("quyeern", "quyển").
test_case("quyenre", "quyển").
test_case("quyerne", "quyển").
test_case("quyener", "quyển").
test_case("quyeenr", "quyển").
test_case("quyenej", "quyện").
test_case("quyeejn", "quyện").
test_case("quyeenj", "quyện").
test_case("quyenje", "quyện").
test_case("quyejne", "quyện").
test_case("quyejen", "quyện").
test_case("beps", "bép").
test_case("besp", "bép").
test_case("bejp", "bẹp").
test_case("bepj", "bẹp").
test_case("bifu", "bìu").
test_case("biuf", "bìu").
test_case("bius", "bíu").
test_case("bisu", "bíu").
test_case("biux", "bĩu").
test_case("bixu", "bĩu").
test_case("biur", "bỉu").
test_case("biru", "bỉu").
test_case("biuj", "bịu").
test_case("biju", "bịu").
test_case("khuyuj", "khuỵu").
test_case("khuyju", "khuỵu").
test_case("khuyur", "khuỷu").
test_case("khuyru", "khuỷu").
test_case("boio", "bôi").
test_case("booi", "bôi").
test_case("bosoi", "bối").
test_case("boios", "bối").
test_case("boiso", "bối").
test_case("bosio", "bối").
test_case("boois", "bối").
test_case("boosi", "bối").
test_case("boofi", "bồi").
test_case("boiof", "bồi").
test_case("bofoi", "bồi").
test_case("bofio", "bồi").
test_case("boifo", "bồi").
test_case("booif", "bồi").
test_case("boiro", "bổi").
test_case("boior", "bổi").
test_case("borio", "bổi").
test_case("boori", "bổi").
test_case("booir", "bổi").
test_case("boroi", "bổi").
test_case("boijo", "bội").
test_case("boioj", "bội").
test_case("booij", "bội").
test_case("booji", "bội").
test_case("bojoi", "bội").
test_case("bojio", "bội").
test_case("coiox", "cỗi").
test_case("coixo", "cỗi").
test_case("cooxi", "cỗi").
test_case("cooix", "cỗi").
test_case("coxoi", "cỗi").
test_case("coxio", "cỗi").
test_case("huee", "huê").
test_case("huefe", "huề").
test_case("hueef", "huề").
test_case("hueej", "huệ").
test_case("hueje", "huệ").
test_case("nhuese", "nhuế").
test_case("nhuees", "nhuế").
test_case("thueer", "thuể").
test_case("thuere", "thuể").
test_case("buwng", "bưng").
test_case("bunwg", "bưng").
test_case("bungw", "bưng").
test_case("buswng", "bứng").
test_case("bunwgs", "bứng").
test_case("buwnsg", "bứng").
test_case("busnwg", "bứng").
test_case("bunsgw", "bứng").
test_case("bungsw", "bứng").
test_case("bunwsg", "bứng").
test_case("bungws", "bứng").
test_case("buwngs", "bứng").
test_case("bunswg", "bứng").
test_case("busngw", "bứng").
test_case("buwsng", "bứng").
test_case("bufwng", "bừng").
test_case("buwngf", "bừng").
test_case("buwnfg", "bừng").
test_case("bungwf", "bừng").
test_case("bunfgw", "bừng").
test_case("bufnwg", "bừng").
test_case("bunfwg", "bừng").
test_case("bufngw", "bừng").
test_case("bunwgf", "bừng").
test_case("bungfw", "bừng").
test_case("buwfng", "bừng").
test_case("bunwfg", "bừng").
test_case("bunwgr", "bửng").
test_case("buwnrg", "bửng").
test_case("bungrw", "bửng").
test_case("bungwr", "bửng").
test_case("bunrgw", "bửng").
test_case("buwrng", "bửng").
test_case("burnwg", "bửng").
test_case("burwng", "bửng").
test_case("burngw", "bửng").
test_case("buwngr", "bửng").
test_case("bunwrg", "bửng").
test_case("bunrwg", "bửng").
test_case("chungxw", "chững").
test_case("chunxwg", "chững").
test_case("chuwnxg", "chững").
test_case("chuwxng", "chững").
test_case("chuxwng", "chững").
test_case("chuxngw", "chững").
test_case("chunwxg", "chững").
test_case("chuwngx", "chững").
test_case("chuxnwg", "chững").
test_case("chungwx", "chững").
test_case("chunwgx", "chững").
test_case("chunxgw", "chững").
test_case("dujngw", "dựng").
test_case("dungwj", "dựng").
test_case("dunjwg", "dựng").
test_case("dunwjg", "dựng").
test_case("duwnjg", "dựng").
test_case("dungjw", "dựng").
test_case("dunjgw", "dựng").
test_case("duwjng", "dựng").
test_case("dujnwg", "dựng").
test_case("dujwng", "dựng").
test_case("duwngj", "dựng").
test_case("dunwgj", "dựng").
test_case("buotos", "buốt").
test_case("buosot", "buốt").
test_case("buosto", "buốt").
test_case("buoots", "buốt").
test_case("buotso", "buốt").
test_case("buoost", "buốt").
test_case("buojot", "buột").
test_case("buootj", "buột").
test_case("buotjo", "buột").
test_case("buoojt", "buột").
test_case("buojto", "buột").
test_case("buotoj", "buột").
test_case("bosto", "bốt").
test_case("boots", "bốt").
test_case("boost", "bốt").
test_case("bosot", "bốt").
test_case("botso", "bốt").
test_case("botos", "bốt").
test_case("bojot", "bột").
test_case("bojto", "bột").
test_case("botoj", "bột").
test_case("bootj", "bột").
test_case("botjo", "bột").
test_case("boojt", "bột").
test_case("chuarna", "chuẩn").
test_case("chuanra", "chuẩn").
test_case("chuaran", "chuẩn").
test_case("chuaanr", "chuẩn").
test_case("chuanar", "chuẩn").
test_case("chuaarn", "chuẩn").
test_case("huaan", "huân").
test_case("huana", "huân").
test_case("huanas", "huấn").
test_case("huansa", "huấn").
test_case("huasan", "huấn").
test_case("huaans", "huấn").
test_case("huaasn", "huấn").
test_case("huasna", "huấn").
test_case("luanaj", "luận").
test_case("luajan", "luận").
test_case("luaajn", "luận").
test_case("luajna", "luận").
test_case("luaanj", "luận").
test_case("luanja", "luận").
test_case("nhuanaf", "nhuần").
test_case("nhuaafn", "nhuần").
test_case("nhuaanf", "nhuần").
test_case("nhuafna", "nhuần").
test_case("nhuanfa", "nhuần").
test_case("nhuafan", "nhuần").
test_case("thuanxa", "thuẫn").
test_case("thuaxna", "thuẫn").
test_case("thuaaxn", "thuẫn").
test_case("thuaanx", "thuẫn").
test_case("thuanax", "thuẫn").
test_case("thuaxan", "thuẫn").
test_case("bonog", "bông").
test_case("bongo", "bông").
test_case("boong", "bông").
test_case("bongso", "bống").
test_case("bonosg", "bống").
test_case("bonsog", "bống").
test_case("bosngo", "bống").
test_case("bongos", "bống").
test_case("bonogs", "bống").
test_case("boosng", "bống").
test_case("bosong", "bống").
test_case("boonsg", "bống").
test_case("bonsgo", "bống").
test_case("bosnog", "bống").
test_case("boongs", "bống").
test_case("bonfgo", "bồng").
test_case("bonogf", "bồng").
test_case("bonfog", "bồng").
test_case("bongfo", "bồng").
test_case("bofong", "bồng").
test_case("bofnog", "bồng").
test_case("boofng", "bồng").
test_case("bonofg", "bồng").
test_case("boonfg", "bồng").
test_case("bongof", "bồng").
test_case("bofngo", "bồng").
test_case("boongf", "bồng").
test_case("bonorg", "bổng").
test_case("boorng", "bổng").
test_case("bonrgo", "bổng").
test_case("borngo", "bổng").
test_case("bornog", "bổng").
test_case("bongro", "bổng").
test_case("bonrog", "bổng").
test_case("bonogr", "bổng").
test_case("bongor", "bổng").
test_case("boonrg", "bổng").
test_case("boongr", "bổng").
test_case("borong", "bổng").
test_case("bonxgo", "bỗng").
test_case("booxng", "bỗng").
test_case("boxnog", "bỗng").
test_case("boonxg", "bỗng").
test_case("bongox", "bỗng").
test_case("bonxog", "bỗng").
test_case("boxong", "bỗng").
test_case("bonogx", "bỗng").
test_case("boxngo", "bỗng").
test_case("bongxo", "bỗng").
test_case("bonoxg", "bỗng").
test_case("boongx", "bỗng").
test_case("bonjog", "bộng").
test_case("bojnog", "bộng").
test_case("boojng", "bộng").
test_case("bonojg", "bộng").
test_case("bonogj", "bộng").
test_case("bongoj", "bộng").
test_case("bongjo", "bộng").
test_case("boongj", "bộng").
test_case("bojngo", "bộng").
test_case("bonjgo", "bộng").
test_case("boonjg", "bộng").
test_case("bojong", "bộng").
test_case("bieesu", "biếu").
test_case("biesue", "biếu").
test_case("bieuse", "biếu").
test_case("bieseu", "biếu").
test_case("bieeus", "biếu").
test_case("bieues", "biếu").
test_case("bierue", "biểu").
test_case("bieuer", "biểu").
test_case("biereu", "biểu").
test_case("bieure", "biểu").
test_case("bieeru", "biểu").
test_case("bieeur", "biểu").
test_case("chieue", "chiêu").
test_case("chieeu", "chiêu").
test_case("chieuef", "chiều").
test_case("chiefeu", "chiều").
test_case("chieeuf", "chiều").
test_case("chieefu", "chiều").
test_case("chiefue", "chiều").
test_case("chieufe", "chiều").
test_case("dieuxe", "diễu").
test_case("dieuex", "diễu").
test_case("dieeux", "diễu").
test_case("diexeu", "diễu").
test_case("diexue", "diễu").
test_case("dieexu", "diễu").
test_case("dieeuj", "diệu").
test_case("dieuje", "diệu").
test_case("dieeju", "diệu").
test_case("diejeu", "diệu").
test_case("diejue", "diệu").
test_case("dieuej", "diệu").
test_case("choawn", "choăn").
test_case("choanw", "choăn").
test_case("hoanwr", "hoẳn").
test_case("hoawnr", "hoẳn").
test_case("hoawrn", "hoẳn").
test_case("hoarwn", "hoẳn").
test_case("hoarnw", "hoẳn").
test_case("hoanrw", "hoẳn").
test_case("khoawsn", "khoắn").
test_case("khoaswn", "khoắn").
test_case("khoansw", "khoắn").
test_case("khoanws", "khoắn").
test_case("khoasnw", "khoắn").
test_case("khoawns", "khoắn").
test_case("ngoafwn", "ngoằn").
test_case("ngoawnf", "ngoằn").
test_case("ngoanfw", "ngoằn").
test_case("ngoawfn", "ngoằn").
test_case("ngoafnw", "ngoằn").
test_case("ngoanwf", "ngoằn").
test_case("bof", "bò").
test_case("bos", "bó").
test_case("box", "bõ").
test_case("boj", "bọ").
test_case("bor", "bỏ").
test_case("ddo", "đo").
test_case("dod", "đo").
test_case("hoamw", "hoăm").
test_case("hoawm", "hoăm").
test_case("hoasmw", "hoắm").
test_case("hoamsw", "hoắm").
test_case("hoamws", "hoắm").
test_case("hoawms", "hoắm").
test_case("hoawsm", "hoắm").
test_case("hoaswm", "hoắm").
test_case("khoafwm", "khoằm").
test_case("khoafmw", "khoằm").
test_case("khoawfm", "khoằm").
test_case("khoamwf", "khoằm").
test_case("khoamfw", "khoằm").
test_case("khoawmf", "khoằm").
test_case("buowng", "bương").
% test_case("buwowng", "bương").
% test_case("buwongw", "bương").
% test_case("buwonwg", "bương").
test_case("buongw", "bương").
test_case("buonwg", "bương").
% test_case("buwownsg", "bướng").
% test_case("buwongws", "bướng").
% test_case("buwowngs", "bướng").
% test_case("buwoswng", "bướng").
% test_case("buwosngw", "bướng").
test_case("buoswng", "bướng").
% test_case("buwonwsg", "bướng").
test_case("buosnwg", "bướng").
test_case("buosngw", "bướng").
test_case("buongsw", "bướng").
test_case("buongws", "bướng").
test_case("buonwgs", "bướng").
test_case("buownsg", "bướng").
test_case("buonsgw", "bướng").
% test_case("buwosnwg", "bướng").
% test_case("buwonwgs", "bướng").
test_case("buonwsg", "bướng").
% test_case("buwowsng", "bướng").
% test_case("buwonsgw", "bướng").
% test_case("buwonswg", "bướng").
test_case("buowngs", "bướng").
% test_case("buwongsw", "bướng").
test_case("buonswg", "bướng").
test_case("buowsng", "bướng").
test_case("chuonfgw", "chường").
% test_case("chuwongfw", "chường").
% test_case("chuwofwng", "chường").
% test_case("chuwofnwg", "chường").
test_case("chuonwgf", "chường").
% test_case("chuwowfng", "chường").
% test_case("chuwonfgw", "chường").
test_case("chuownfg", "chường").
% test_case("chuwonwgf", "chường").
% test_case("chuwownfg", "chường").
% test_case("chuwowngf", "chường").
test_case("chuofwng", "chường").
test_case("chuongfw", "chường").
test_case("chuowfng", "chường").
% test_case("chuwofngw", "chường").
test_case("chuofngw", "chường").
test_case("chuofnwg", "chường").
test_case("chuowngf", "chường").
test_case("chuongwf", "chường").
% test_case("chuwongwf", "chường").
test_case("chuonfwg", "chường").
% test_case("chuwonfwg", "chường").
test_case("chuonwfg", "chường").
% test_case("chuwonwfg", "chường").
% test_case("chuwongrw", "chưởng").
% test_case("chuwornwg", "chưởng").
test_case("chuowrng", "chưởng").
% test_case("chuworwng", "chưởng").
test_case("chuonwgr", "chưởng").
test_case("chuorngw", "chưởng").
test_case("chuongrw", "chưởng").
test_case("chuorwng", "chưởng").
% test_case("chuwownrg", "chưởng").
% test_case("chuworngw", "chưởng").
test_case("chuonwrg", "chưởng").
% test_case("chuwonwrg", "chưởng").
test_case("chuonrwg", "chưởng").
% test_case("chuwonwgr", "chưởng").
test_case("chuownrg", "chưởng").
test_case("chuornwg", "chưởng").
% test_case("chuwonrwg", "chưởng").
test_case("chuowngr", "chưởng").
% test_case("chuwonrgw", "chưởng").
test_case("chuongwr", "chưởng").
% test_case("chuwongwr", "chưởng").
% test_case("chuwowrng", "chưởng").
test_case("chuonrgw", "chưởng").
% test_case("chuwowngr", "chưởng").
test_case("chuoxwng", "chưỡng").
test_case("chuoxnwg", "chưỡng").
% test_case("chuwonwxg", "chưỡng").
test_case("chuoxngw", "chưỡng").
% test_case("chuwowxng", "chưỡng").
% test_case("chuwoxwng", "chưỡng").
% test_case("chuwoxnwg", "chưỡng").
% test_case("chuwonxgw", "chưỡng").
test_case("chuowngx", "chưỡng").
% test_case("chuwonwgx", "chưỡng").
% test_case("chuwoxngw", "chưỡng").
test_case("chuowxng", "chưỡng").
% test_case("chuwownxg", "chưỡng").
test_case("chuonwgx", "chưỡng").
% test_case("chuwongwx", "chưỡng").
test_case("chuonxwg", "chưỡng").
% test_case("chuwongxw", "chưỡng").
test_case("chuownxg", "chưỡng").
test_case("chuonxgw", "chưỡng").
test_case("chuongxw", "chưỡng").
test_case("chuongwx", "chưỡng").
test_case("chuonwxg", "chưỡng").
% test_case("chuwonxwg", "chưỡng").
% test_case("chuwowngx", "chưỡng").
% test_case("duwonwjg", "dượng").
test_case("duojnwg", "dượng").
test_case("duonwgj", "dượng").
test_case("duowjng", "dượng").
test_case("duownjg", "dượng").
% test_case("duwojnwg", "dượng").
% test_case("duwongwj", "dượng").
test_case("duojngw", "dượng").
test_case("duongjw", "dượng").
test_case("duojwng", "dượng").
% test_case("duwonjgw", "dượng").
% test_case("duwowjng", "dượng").
test_case("duonjwg", "dượng").
test_case("duonwjg", "dượng").
test_case("duonjgw", "dượng").
% test_case("duwongjw", "dượng").
test_case("duowngj", "dượng").
% test_case("duwojngw", "dượng").
% test_case("duwonwgj", "dượng").
% test_case("duwowngj", "dượng").
% test_case("duwownjg", "dượng").
test_case("duongwj", "dượng").
% test_case("duwojwng", "dượng").
% test_case("duwonjwg", "dượng").
test_case("choajc", "choạc").
test_case("choacj", "choạc").
test_case("hoasc", "hoác").
test_case("hoacs", "hoác").
test_case("bafu", "bàu").
test_case("bauf", "bàu").
test_case("basu", "báu").
test_case("baus", "báu").
test_case("baju", "bạu").
test_case("bauj", "bạu").
test_case("baru", "bảu").
test_case("baur", "bảu").
test_case("dadu", "đau").
test_case("ddau", "đau").
test_case("daud", "đau").
test_case("bacsh", "bách").
test_case("basch", "bách").
test_case("bachs", "bách").
test_case("bacjh", "bạch").
test_case("bajch", "bạch").
test_case("bachj", "bạch").
test_case("bucj", "bục").
test_case("bujc", "bục").
test_case("chusc", "chúc").
test_case("chucs", "chúc").
test_case("khuatsa", "khuất").
test_case("khuasta", "khuất").
test_case("khuatas", "khuất").
test_case("khuaats", "khuất").
test_case("khuasat", "khuất").
test_case("khuaast", "khuất").
test_case("luataj", "luật").
test_case("luajat", "luật").
test_case("luajta", "luật").
test_case("luatja", "luật").
test_case("luaajt", "luật").
test_case("luaatj", "luật").
test_case("binj", "bịn").
test_case("bijn", "bịn").
test_case("chins", "chín").
test_case("chisn", "chín").
test_case("chixn", "chĩn").
test_case("chinx", "chĩn").
test_case("chinr", "chỉn").
test_case("chirn", "chỉn").
test_case("gifn", "gìn").
test_case("ginf", "gìn").
test_case("dind", "đin").
test_case("didn", "đin").
test_case("ddin", "đin").
test_case("bieces", "biếc").
test_case("biesce", "biếc").
test_case("biesec", "biếc").
test_case("biecse", "biếc").
test_case("bieesc", "biếc").
test_case("bieecs", "biếc").
test_case("diejec", "diệc").
test_case("diecje", "diệc").
test_case("dieejc", "diệc").
test_case("diecej", "diệc").
test_case("diejce", "diệc").
test_case("dieecj", "diệc").
test_case("bastw", "bắt").
test_case("bawst", "bắt").
test_case("bawts", "bắt").
test_case("batsw", "bắt").
test_case("batws", "bắt").
test_case("baswt", "bắt").
test_case("bajtw", "bặt").
test_case("batwj", "bặt").
test_case("bawtj", "bặt").
test_case("bawjt", "bặt").
test_case("bajwt", "bặt").
test_case("batjw", "bặt").
test_case("bef", "bè").
test_case("bes", "bé").
test_case("bej", "bẹ").
test_case("ber", "bẻ").
test_case("bex", "bẽ").
test_case("dde", "đe").
test_case("ded", "đe").
test_case("bieste", "biết").
test_case("bieets", "biết").
test_case("bieest", "biết").
test_case("bietes", "biết").
test_case("bieset", "biết").
test_case("bietse", "biết").
test_case("biejet", "biệt").
test_case("biejte", "biệt").
test_case("bietej", "biệt").
test_case("bietje", "biệt").
test_case("bieejt", "biệt").
test_case("bieetj", "biệt").
test_case("cooocs", "coóc").
test_case("cooosc", "coóc").
test_case("bofi", "bòi").
test_case("boif", "bòi").
test_case("bois", "bói").
test_case("bosi", "bói").
test_case("bori", "bỏi").
test_case("boir", "bỏi").
test_case("choij", "chọi").
test_case("choji", "chọi").
test_case("coix", "cõi").
test_case("coxi", "cõi").
test_case("doid", "đoi").
test_case("ddoi", "đoi").
test_case("dodi", "đoi").
test_case("bomo", "bôm").
test_case("boom", "bôm").
test_case("bomof", "bồm").
test_case("boofm", "bồm").
test_case("bofmo", "bồm").
test_case("bofom", "bồm").
test_case("bomfo", "bồm").
test_case("boomf", "bồm").
test_case("choxom", "chỗm").
test_case("chomox", "chỗm").
test_case("chomxo", "chỗm").
test_case("choxmo", "chỗm").
test_case("chooxm", "chỗm").
test_case("choomx", "chỗm").
test_case("comos", "cốm").
test_case("cosom", "cốm").
test_case("cosmo", "cốm").
test_case("cooms", "cốm").
test_case("coosm", "cốm").
test_case("comso", "cốm").
test_case("coomj", "cộm").
test_case("cojmo", "cộm").
test_case("cojom", "cộm").
test_case("comoj", "cộm").
test_case("comjo", "cộm").
test_case("coojm", "cộm").
test_case("hoomr", "hổm").
test_case("horom", "hổm").
test_case("hoorm", "hổm").
test_case("homro", "hổm").
test_case("homor", "hổm").
test_case("hormo", "hổm").
test_case("bamas", "bấm").
test_case("baams", "bấm").
test_case("baasm", "bấm").
test_case("basma", "bấm").
test_case("bamsa", "bấm").
test_case("basam", "bấm").
test_case("bamaf", "bầm").
test_case("bafma", "bầm").
test_case("bafam", "bầm").
test_case("baamf", "bầm").
test_case("bamfa", "bầm").
test_case("baafm", "bầm").
test_case("bamra", "bẩm").
test_case("baamr", "bẩm").
test_case("baram", "bẩm").
test_case("barma", "bẩm").
test_case("bamar", "bẩm").
test_case("baarm", "bẩm").
test_case("baxma", "bẫm").
test_case("baaxm", "bẫm").
test_case("bamax", "bẫm").
test_case("bamxa", "bẫm").
test_case("baamx", "bẫm").
test_case("baxam", "bẫm").
test_case("baamj", "bậm").
test_case("bajma", "bậm").
test_case("bamaj", "bậm").
test_case("baajm", "bậm").
test_case("bamja", "bậm").
test_case("bajam", "bậm").
test_case("chaam", "châm").
test_case("chama", "châm").
test_case("choefn", "choèn").
test_case("choenf", "choèn").
test_case("hoenr", "hoẻn").
test_case("hoern", "hoẻn").
test_case("bawn", "băn").
test_case("banw", "băn").
test_case("banws", "bắn").
test_case("basnw", "bắn").
test_case("baswn", "bắn").
test_case("bansw", "bắn").
test_case("bawns", "bắn").
test_case("bawsn", "bắn").
test_case("bafnw", "bằn").
test_case("bawfn", "bằn").
test_case("bafwn", "bằn").
test_case("bawnf", "bằn").
test_case("banwf", "bằn").
test_case("banfw", "bằn").
test_case("barnw", "bẳn").
test_case("banwr", "bẳn").
test_case("banrw", "bẳn").
test_case("barwn", "bẳn").
test_case("bawrn", "bẳn").
test_case("bawnr", "bẳn").
test_case("bawnj", "bặn").
test_case("bawjn", "bặn").
test_case("bajwn", "bặn").
test_case("banjw", "bặn").
test_case("bajnw", "bặn").
test_case("banwj", "bặn").
test_case("chawnx", "chẵn").
test_case("chaxnw", "chẵn").
test_case("chanwx", "chẵn").
test_case("chawxn", "chẵn").
test_case("chaxwn", "chẵn").
test_case("chanxw", "chẵn").
test_case("buofom", "buồm").
test_case("buomof", "buồm").
test_case("buoomf", "buồm").
test_case("buofmo", "buồm").
test_case("buoofm", "buồm").
test_case("buomfo", "buồm").
test_case("chuoom", "chuôm").
test_case("chuomo", "chuôm").
test_case("cuoxmo", "cuỗm").
test_case("cuoomx", "cuỗm").
test_case("cuoxom", "cuỗm").
test_case("cuomxo", "cuỗm").
test_case("cuomox", "cuỗm").
test_case("cuooxm", "cuỗm").
test_case("luoomj", "luộm").
test_case("luoojm", "luộm").
test_case("luojom", "luộm").
test_case("luojmo", "luộm").
test_case("luomoj", "luộm").
test_case("luomjo", "luộm").
test_case("nhuomos", "nhuốm").
test_case("nhuosom", "nhuốm").
test_case("nhuoosm", "nhuốm").
test_case("nhuosmo", "nhuốm").
test_case("nhuooms", "nhuốm").
test_case("nhuomso", "nhuốm").
test_case("bups", "búp").
test_case("busp", "búp").
test_case("bujp", "bụp").
test_case("bupj", "bụp").
% test_case("buwomw", "bươm").
% test_case("buwowm", "bươm").
test_case("buowm", "bươm").
test_case("buomw", "bươm").
% test_case("buwowsm", "bướm").
test_case("buowsm", "bướm").
test_case("buomws", "bướm").
test_case("buowms", "bướm").
% test_case("buwomsw", "bướm").
test_case("buosmw", "bướm").
test_case("buomsw", "bướm").
test_case("buoswm", "bướm").
% test_case("buwomws", "bướm").
% test_case("buwosmw", "bướm").
% test_case("buwowms", "bướm").
% test_case("buwoswm", "bướm").
test_case("chuofwm", "chườm").
% test_case("chuwowfm", "chườm").
% test_case("chuwofwm", "chườm").
% test_case("chuwowmf", "chườm").
% test_case("chuwomwf", "chườm").
test_case("chuomfw", "chườm").
test_case("chuomwf", "chườm").
test_case("chuofmw", "chườm").
% test_case("chuwomfw", "chườm").
test_case("chuowfm", "chườm").
test_case("chuowmf", "chườm").
% test_case("chuwofmw", "chườm").
% test_case("guwowjm", "gượm").
test_case("guowjm", "gượm").
% test_case("guwomwj", "gượm").
test_case("guomjw", "gượm").
% test_case("guwojmw", "gượm").
% test_case("guwomjw", "gượm").
test_case("guojmw", "gượm").
test_case("guojwm", "gượm").
test_case("guomwj", "gượm").
test_case("guowmj", "gượm").
% test_case("guwowmj", "gượm").
% test_case("guwojwm", "gượm").
test_case("bafng", "bàng").
test_case("banfg", "bàng").
test_case("bangf", "bàng").
test_case("bansg", "báng").
test_case("bangs", "báng").
test_case("basng", "báng").
test_case("barng", "bảng").
test_case("banrg", "bảng").
test_case("bangr", "bảng").
test_case("chanjg", "chạng").
test_case("chajng", "chạng").
test_case("changj", "chạng").
test_case("hanxg", "hãng").
test_case("hangx", "hãng").
test_case("haxng", "hãng").
test_case("dangd", "đang").
test_case("dadng", "đang").
test_case("ddang", "đang").
test_case("dandg", "đang").
test_case("chiesep", "chiếp").
test_case("chieeps", "chiếp").
test_case("chiepse", "chiếp").
test_case("chiepes", "chiếp").
test_case("chieesp", "chiếp").
test_case("chiespe", "chiếp").
test_case("dieepj", "diệp").
test_case("diepje", "diệp").
test_case("diejpe", "diệp").
test_case("diejep", "diệp").
test_case("dieejp", "diệp").
test_case("diepej", "diệp").
test_case("khoefo", "khoèo").
test_case("khoeof", "khoèo").
test_case("ngoeso", "ngoéo").
test_case("ngoeos", "ngoéo").
test_case("yeeu", "yêu").
test_case("yeue", "yêu").
test_case("yeuse", "yếu").
test_case("yeues", "yếu").
test_case("yeeus", "yếu").
test_case("yeesu", "yếu").
test_case("yeseu", "yếu").
test_case("yesue", "yếu").
test_case("yereu", "yểu").
test_case("yeeur", "yểu").
test_case("yerue", "yểu").
test_case("yeuer", "yểu").
test_case("yeure", "yểu").
test_case("yeeru", "yểu").
test_case("bipj", "bịp").
test_case("bijp", "bịp").
test_case("chips", "chíp").
test_case("chisp", "chíp").
test_case("chosa", "chóa").
test_case("choas", "chóa").
test_case("doja", "dọa").
test_case("doaj", "dọa").
test_case("hofa", "hòa").
test_case("hoaf", "hòa").
test_case("hora", "hỏa").
test_case("hoar", "hỏa").
test_case("ngoxa", "ngõa").
test_case("ngoax", "ngõa").
test_case("basap", "bấp").
test_case("baasp", "bấp").
test_case("baspa", "bấp").
test_case("baaps", "bấp").
test_case("bapas", "bấp").
test_case("bapsa", "bấp").
test_case("bapaj", "bập").
test_case("bapja", "bập").
test_case("bajpa", "bập").
test_case("baajp", "bập").
test_case("bajap", "bập").
test_case("baapj", "bập").
test_case("besng", "béng").
test_case("bensg", "béng").
test_case("bengs", "béng").
test_case("kengr", "kẻng").
test_case("kerng", "kẻng").
test_case("kenrg", "kẻng").
test_case("mefng", "mèng").
test_case("mengf", "mèng").
test_case("menfg", "mèng").
test_case("hoays", "hoáy").
test_case("hoasy", "hoáy").
test_case("ngoary", "ngoảy").
test_case("ngoayr", "ngoảy").
test_case("kys", "ký").
test_case("kyf", "kỳ").
test_case("kyj", "kỵ").
test_case("kyr", "kỷ").
test_case("kyx", "kỹ").
test_case("boo", "bô").
test_case("boos", "bố").
test_case("boso", "bố").
test_case("bofo", "bồ").
test_case("boof", "bồ").
test_case("boor", "bổ").
test_case("boro", "bổ").
test_case("boox", "bỗ").
test_case("boxo", "bỗ").
test_case("bojo", "bộ").
test_case("booj", "bộ").
test_case("choaif", "choài").
test_case("choafi", "choài").
test_case("choasi", "choái").
test_case("choais", "choái").
test_case("choaix", "choãi").
test_case("choaxi", "choãi").
test_case("hoaij", "hoại").
test_case("hoaji", "hoại").
test_case("hoair", "hoải").
test_case("hoari", "hoải").
test_case("chuyene", "chuyên").
test_case("chuyeen", "chuyên").
test_case("chuyesen", "chuyến").
test_case("chuyesne", "chuyến").
test_case("chuyeesn", "chuyến").
test_case("chuyense", "chuyến").
test_case("chuyeens", "chuyến").
test_case("chuyenes", "chuyến").
test_case("chuyefne", "chuyền").
test_case("chuyeenf", "chuyền").
test_case("chuyenef", "chuyền").
test_case("chuyeefn", "chuyền").
test_case("chuyenfe", "chuyền").
test_case("chuyefen", "chuyền").
test_case("chuyeren", "chuyển").
test_case("chuyener", "chuyển").
test_case("chuyerne", "chuyển").
test_case("chuyeern", "chuyển").
test_case("chuyeenr", "chuyển").
test_case("chuyenre", "chuyển").
test_case("chuyenje", "chuyện").
test_case("chuyeenj", "chuyện").
test_case("chuyeejn", "chuyện").
test_case("chuyejne", "chuyện").
test_case("chuyejen", "chuyện").
test_case("chuyenej", "chuyện").
test_case("huyexne", "huyễn").
test_case("huyenxe", "huyễn").
test_case("huyeenx", "huyễn").
test_case("huyeexn", "huyễn").
test_case("huyenex", "huyễn").
test_case("huyexen", "huyễn").
test_case("bono", "bôn").
test_case("boon", "bôn").
test_case("bonos", "bốn").
test_case("boosn", "bốn").
test_case("boson", "bốn").
test_case("boons", "bốn").
test_case("bonso", "bốn").
test_case("bosno", "bốn").
test_case("bofno", "bồn").
test_case("boofn", "bồn").
test_case("bonof", "bồn").
test_case("boonf", "bồn").
test_case("bofon", "bồn").
test_case("bonfo", "bồn").
test_case("bonor", "bổn").
test_case("boron", "bổn").
test_case("boonr", "bổn").
test_case("borno", "bổn").
test_case("bonro", "bổn").
test_case("boorn", "bổn").
test_case("bonoj", "bộn").
test_case("boonj", "bộn").
test_case("bojno", "bộn").
test_case("boojn", "bộn").
test_case("bonjo", "bộn").
test_case("bojon", "bộn").
test_case("hoxno", "hỗn").
test_case("hoxon", "hỗn").
test_case("honxo", "hỗn").
test_case("honox", "hỗn").
test_case("hooxn", "hỗn").
test_case("hoonx", "hỗn").
test_case("hoatj", "hoạt").
test_case("hoajt", "hoạt").
test_case("khoats", "khoát").
test_case("khoast", "khoát").
test_case("choajp", "choạp").
test_case("choapj", "choạp").
test_case("buoojc", "buộc").
test_case("buocoj", "buộc").
test_case("buojco", "buộc").
test_case("buoocj", "buộc").
test_case("buojoc", "buộc").
test_case("buocjo", "buộc").
test_case("chuosoc", "chuốc").
test_case("chuoosc", "chuốc").
test_case("chuoocs", "chuốc").
test_case("chuocos", "chuốc").
test_case("chuosco", "chuốc").
test_case("chuocso", "chuốc").
test_case("choes", "chóe").
test_case("chose", "chóe").
test_case("choje", "chọe").
test_case("choej", "chọe").
test_case("hoef", "hòe").
test_case("hofe", "hòe").
test_case("khore", "khỏe").
test_case("khoer", "khỏe").
test_case("toex", "tõe").
test_case("toxe", "tõe").
test_case("been", "bên").
test_case("bene", "bên").
test_case("besne", "bến").
test_case("beens", "bến").
test_case("bense", "bến").
test_case("besen", "bến").
test_case("benes", "bến").
test_case("beesn", "bến").
test_case("benfe", "bền").
test_case("beenf", "bền").
test_case("befen", "bền").
test_case("befne", "bền").
test_case("beefn", "bền").
test_case("benef", "bền").
test_case("bejne", "bện").
test_case("benje", "bện").
test_case("beenj", "bện").
test_case("beejn", "bện").
test_case("benej", "bện").
test_case("bejen", "bện").
test_case("hener", "hển").
test_case("heenr", "hển").
test_case("heren", "hển").
test_case("henre", "hển").
test_case("heern", "hển").
test_case("herne", "hển").
test_case("phexne", "phễn").
test_case("pheenx", "phễn").
test_case("pheexn", "phễn").
test_case("phenex", "phễn").
test_case("phexen", "phễn").
test_case("phenxe", "phễn").
test_case("gieeng", "giêng").
test_case("gieneg", "giêng").
test_case("gienge", "giêng").
test_case("giesneg", "giếng").
test_case("giengse", "giếng").
test_case("gieengs", "giếng").
test_case("gienges", "giếng").
test_case("gienseg", "giếng").
test_case("gienegs", "giếng").
test_case("gieseng", "giếng").
test_case("gieesng", "giếng").
test_case("gieensg", "giếng").
test_case("giensge", "giếng").
test_case("giesnge", "giếng").
test_case("gienesg", "giếng").
test_case("giengef", "giềng").
test_case("giefneg", "giềng").
test_case("gienegf", "giềng").
test_case("gieengf", "giềng").
test_case("giefeng", "giềng").
test_case("gienfeg", "giềng").
test_case("gieenfg", "giềng").
test_case("giengfe", "giềng").
test_case("giefnge", "giềng").
test_case("gienefg", "giềng").
test_case("gienfge", "giềng").
test_case("gieefng", "giềng").
test_case("buofio", "buồi").
test_case("buoiof", "buồi").
test_case("buooif", "buồi").
test_case("buoofi", "buồi").
test_case("buoifo", "buồi").
test_case("buofoi", "buồi").
test_case("buoroi", "buổi").
test_case("buoiro", "buổi").
test_case("buorio", "buổi").
test_case("buoori", "buổi").
test_case("buooir", "buổi").
test_case("buoior", "buổi").
test_case("chuooi", "chuôi").
test_case("chuoio", "chuôi").
test_case("chuosio", "chuối").
test_case("chuoiso", "chuối").
test_case("chuosoi", "chuối").
test_case("chuoois", "chuối").
test_case("chuoios", "chuối").
test_case("chuoosi", "chuối").
test_case("chuoxio", "chuỗi").
test_case("chuoiox", "chuỗi").
test_case("chuooxi", "chuỗi").
test_case("chuooix", "chuỗi").
test_case("chuoxoi", "chuỗi").
test_case("chuoixo", "chuỗi").
test_case("chuooji", "chuội").
test_case("chuoijo", "chuội").
test_case("chuooij", "chuội").
test_case("chuojio", "chuội").
test_case("chuoioj", "chuội").
test_case("chuojoi", "chuội").
test_case("boswt", "bớt").
test_case("bowts", "bớt").
test_case("bostw", "bớt").
test_case("bowst", "bớt").
test_case("botsw", "bớt").
test_case("botws", "bớt").
test_case("botjw", "bợt").
test_case("bojtw", "bợt").
test_case("bowjt", "bợt").
test_case("bojwt", "bợt").
test_case("bowtj", "bợt").
test_case("botwj", "bợt").
test_case("banga", "bâng").
test_case("baang", "bâng").
test_case("banag", "bâng").
test_case("bafnga", "bầng").
test_case("baangf", "bầng").
test_case("banfga", "bầng").
test_case("banafg", "bầng").
test_case("baanfg", "bầng").
test_case("bafang", "bầng").
test_case("bangaf", "bầng").
test_case("bafnag", "bầng").
test_case("baafng", "bầng").
test_case("banagf", "bầng").
test_case("bangfa", "bầng").
test_case("banfag", "bầng").
test_case("cangax", "cẫng").
test_case("caanxg", "cẫng").
test_case("caxnag", "cẫng").
test_case("canxga", "cẫng").
test_case("caaxng", "cẫng").
test_case("canxag", "cẫng").
test_case("cangxa", "cẫng").
test_case("canagx", "cẫng").
test_case("caxang", "cẫng").
test_case("canaxg", "cẫng").
test_case("caangx", "cẫng").
test_case("caxnga", "cẫng").
test_case("haasng", "hấng").
test_case("haansg", "hấng").
test_case("hangsa", "hấng").
test_case("hasnag", "hấng").
test_case("hasang", "hấng").
test_case("hangas", "hấng").
test_case("hasnga", "hấng").
test_case("hansag", "hấng").
test_case("haangs", "hấng").
test_case("hanags", "hấng").
test_case("hanasg", "hấng").
test_case("hansga", "hấng").
test_case("harnga", "hẩng").
test_case("harnag", "hẩng").
test_case("haarng", "hẩng").
test_case("hanarg", "hẩng").
test_case("hangra", "hẩng").
test_case("hanagr", "hẩng").
test_case("haanrg", "hẩng").
test_case("hanrga", "hẩng").
test_case("haangr", "hẩng").
test_case("harang", "hẩng").
test_case("hanrag", "hẩng").
test_case("hangar", "hẩng").
test_case("nanagj", "nậng").
test_case("najnga", "nậng").
test_case("nanajg", "nậng").
test_case("najnag", "nậng").
test_case("nanjag", "nậng").
test_case("najang", "nậng").
test_case("naangj", "nậng").
test_case("naajng", "nậng").
test_case("naanjg", "nậng").
test_case("nanjga", "nậng").
test_case("nangja", "nậng").
test_case("nangaj", "nậng").
test_case("bufi", "bùi").
test_case("buif", "bùi").
test_case("buis", "búi").
test_case("busi", "búi").
test_case("buij", "bụi").
test_case("buji", "bụi").
test_case("chuxi", "chũi").
test_case("chuix", "chũi").
test_case("curi", "củi").
test_case("cuir", "củi").
test_case("ddui", "đui").
test_case("duid", "đui").
test_case("dudi", "đui").
test_case("baay", "bây").
test_case("baya", "bây").
test_case("baasy", "bấy").
test_case("baays", "bấy").
test_case("basya", "bấy").
test_case("baysa", "bấy").
test_case("bayas", "bấy").
test_case("basay", "bấy").
test_case("baayf", "bầy").
test_case("bafya", "bầy").
test_case("bafay", "bầy").
test_case("baafy", "bầy").
test_case("bayfa", "bầy").
test_case("bayaf", "bầy").
test_case("baayr", "bẩy").
test_case("baray", "bẩy").
test_case("bayar", "bẩy").
test_case("bayra", "bẩy").
test_case("baary", "bẩy").
test_case("barya", "bẩy").
test_case("baayx", "bẫy").
test_case("bayax", "bẫy").
test_case("baxya", "bẫy").
test_case("bayxa", "bẫy").
test_case("baxay", "bẫy").
test_case("baaxy", "bẫy").
test_case("baajy", "bậy").
test_case("baayj", "bậy").
test_case("bajya", "bậy").
test_case("bajay", "bậy").
test_case("bayaj", "bậy").
test_case("bayja", "bậy").
test_case("ngoamf", "ngoàm").
test_case("ngoafm", "ngoàm").
test_case("ngoamj", "ngoạm").
test_case("ngoajm", "ngoạm").
test_case("choans", "choán").
test_case("choasn", "choán").
test_case("doaxn", "doãn").
test_case("doanx", "doãn").
test_case("hoanf", "hoàn").
test_case("hoafn", "hoàn").
test_case("hoanj", "hoạn").
test_case("hoajn", "hoạn").
test_case("khoarn", "khoản").
test_case("khoanr", "khoản").
test_case("dodan", "đoan").
test_case("ddoan", "đoan").
test_case("doadn", "đoan").
test_case("doand", "đoan").
test_case("chufy", "chùy").
test_case("chuyf", "chùy").
test_case("husy", "húy").
test_case("huys", "húy").
test_case("huyr", "hủy").
test_case("hury", "hủy").
test_case("luxy", "lũy").
test_case("luyx", "lũy").
test_case("lujy", "lụy").
test_case("luyj", "lụy").
test_case("bawcs", "bắc").
test_case("baswc", "bắc").
test_case("bawsc", "bắc").
test_case("bascw", "bắc").
test_case("bacsw", "bắc").
test_case("bacws", "bắc").
test_case("chawcj", "chặc").
test_case("chacwj", "chặc").
test_case("chacjw", "chặc").
test_case("chawjc", "chặc").
test_case("chajwc", "chặc").
test_case("chajcw", "chặc").
test_case("biemse", "biếm").
test_case("biemes", "biếm").
test_case("biesem", "biếm").
test_case("biesme", "biếm").
test_case("bieesm", "biếm").
test_case("bieems", "biếm").
test_case("chieem", "chiêm").
test_case("chieme", "chiêm").
test_case("diefem", "diềm").
test_case("diemfe", "diềm").
test_case("dieefm", "diềm").
test_case("diemef", "diềm").
test_case("diefme", "diềm").
test_case("dieemf", "diềm").
test_case("diexme", "diễm").
test_case("diexem", "diễm").
test_case("diemex", "diễm").
test_case("dieemx", "diễm").
test_case("dieexm", "diễm").
test_case("diemxe", "diễm").
test_case("hiemer", "hiểm").
test_case("hieemr", "hiểm").
test_case("hierem", "hiểm").
test_case("hierme", "hiểm").
test_case("hieerm", "hiểm").
test_case("hiemre", "hiểm").
test_case("kiejem", "kiệm").
test_case("kiemje", "kiệm").
test_case("kiemej", "kiệm").
test_case("kiejme", "kiệm").
test_case("kieemj", "kiệm").
test_case("kieejm", "kiệm").
test_case("bowm", "bơm").
test_case("bomw", "bơm").
test_case("bofmw", "bờm").
test_case("bomwf", "bờm").
test_case("bowmf", "bờm").
test_case("bowfm", "bờm").
test_case("bofwm", "bờm").
test_case("bomfw", "bờm").
test_case("bowjm", "bợm").
test_case("bowmj", "bợm").
test_case("bomjw", "bợm").
test_case("bojmw", "bợm").
test_case("bomwj", "bợm").
test_case("bojwm", "bợm").
test_case("chomsw", "chớm").
test_case("chowms", "chớm").
test_case("choswm", "chớm").
test_case("chomws", "chớm").
test_case("chosmw", "chớm").
test_case("chowsm", "chớm").
test_case("chorwm", "chởm").
test_case("chomrw", "chởm").
test_case("chowmr", "chởm").
test_case("chowrm", "chởm").
test_case("chomwr", "chởm").
test_case("chormw", "chởm").
test_case("cowxm", "cỡm").
test_case("coxmw", "cỡm").
test_case("comwx", "cỡm").
test_case("coxwm", "cỡm").
test_case("comxw", "cỡm").
test_case("cowmx", "cỡm").
test_case("buongo", "buông").
test_case("buonog", "buông").
test_case("buoong", "buông").
test_case("buonfog", "buồng").
test_case("buoofng", "buồng").
test_case("buoongf", "buồng").
test_case("buofngo", "buồng").
test_case("buongof", "buồng").
test_case("buonofg", "buồng").
test_case("buonfgo", "buồng").
test_case("buofong", "buồng").
test_case("buofnog", "buồng").
test_case("buonogf", "buồng").
test_case("buongfo", "buồng").
test_case("buoonfg", "buồng").
test_case("chuojong", "chuộng").
test_case("chuojngo", "chuộng").
test_case("chuonogj", "chuộng").
test_case("chuongoj", "chuộng").
test_case("chuoonjg", "chuộng").
test_case("chuoojng", "chuộng").
test_case("chuoongj", "chuộng").
test_case("chuojnog", "chuộng").
test_case("chuonjgo", "chuộng").
test_case("chuongjo", "chuộng").
test_case("chuonjog", "chuộng").
test_case("chuonojg", "chuộng").
test_case("cuosong", "cuống").
test_case("cuoosng", "cuống").
test_case("cuongso", "cuống").
test_case("cuosngo", "cuống").
test_case("cuonsgo", "cuống").
test_case("cuonsog", "cuống").
test_case("cuosnog", "cuống").
test_case("cuoonsg", "cuống").
test_case("cuongos", "cuống").
test_case("cuonogs", "cuống").
test_case("cuoongs", "cuống").
test_case("cuonosg", "cuống").
test_case("luongxo", "luỗng").
test_case("luonoxg", "luỗng").
test_case("luonxgo", "luỗng").
test_case("luoongx", "luỗng").
test_case("luoxong", "luỗng").
test_case("luongox", "luỗng").
test_case("luoxngo", "luỗng").
test_case("luooxng", "luỗng").
test_case("luoxnog", "luỗng").
test_case("luonogx", "luỗng").
test_case("luoonxg", "luỗng").
test_case("luonxog", "luỗng").
test_case("thuongor", "thuổng").
test_case("thuoorng", "thuổng").
test_case("thuonrog", "thuổng").
test_case("thuorngo", "thuổng").
test_case("thuoongr", "thuổng").
test_case("thuornog", "thuổng").
test_case("thuonogr", "thuổng").
test_case("thuonorg", "thuổng").
test_case("thuoonrg", "thuổng").
test_case("thuonrgo", "thuổng").
test_case("thuongro", "thuổng").
test_case("thuorong", "thuổng").
test_case("quyts", "quýt").
test_case("quyst", "quýt").
test_case("quyjt", "quỵt").
test_case("quytj", "quỵt").
test_case("bee", "bê").
test_case("bees", "bế").
test_case("bese", "bế").
test_case("befe", "bề").
test_case("beef", "bề").
test_case("bere", "bể").
test_case("beer", "bể").
test_case("bexe", "bễ").
test_case("beex", "bễ").
test_case("beje", "bệ").
test_case("beej", "bệ").
test_case("buwa", "bưa").
test_case("buaw", "bưa").
test_case("buawf", "bừa").
test_case("buafw", "bừa").
test_case("buwfa", "bừa").
test_case("bufwa", "bừa").
test_case("buwaf", "bừa").
test_case("bufaw", "bừa").
test_case("buwra", "bửa").
test_case("buwar", "bửa").
test_case("buarw", "bửa").
test_case("buawr", "bửa").
test_case("burwa", "bửa").
test_case("buraw", "bửa").
test_case("buawx", "bữa").
test_case("buaxw", "bữa").
test_case("buxaw", "bữa").
test_case("buxwa", "bữa").
test_case("buwax", "bữa").
test_case("buwxa", "bữa").
test_case("buwja", "bựa").
test_case("bujaw", "bựa").
test_case("buajw", "bựa").
test_case("buwaj", "bựa").
test_case("bujwa", "bựa").
test_case("buawj", "bựa").
test_case("chuwsa", "chứa").
test_case("chusaw", "chứa").
test_case("chuswa", "chứa").
test_case("chuaws", "chứa").
test_case("chuwas", "chứa").
test_case("chuasw", "chứa").
test_case("beof", "bèo").
test_case("befo", "bèo").
test_case("beso", "béo").
test_case("beos", "béo").
test_case("bejo", "bẹo").
test_case("beoj", "bẹo").
test_case("beor", "bẻo").
test_case("bero", "bẻo").
test_case("bexo", "bẽo").
test_case("beox", "bẽo").
test_case("ddeo", "đeo").
test_case("dedo", "đeo").
test_case("deod", "đeo").
test_case("buw", "bư").
test_case("busw", "bứ").
test_case("buws", "bứ").
test_case("bujw", "bự").
test_case("buwj", "bự").
test_case("chufw", "chừ").
test_case("chuwf", "chừ").
test_case("chuxw", "chữ").
test_case("chuwx", "chữ").
test_case("curw", "cử").
test_case("cuwr", "cử").
test_case("chuesceh", "chuếch").
test_case("chuesech", "chuếch").
test_case("chueecsh", "chuếch").
test_case("chueechs", "chuếch").
test_case("chuechse", "chuếch").
test_case("chuecseh", "chuếch").
test_case("chuesche", "chuếch").
test_case("chueesch", "chuếch").
test_case("chueches", "chuếch").
test_case("chuecesh", "chuếch").
test_case("chuecshe", "chuếch").
test_case("chuecehs", "chuếch").
test_case("chuecjhe", "chuệch").
test_case("chuechej", "chuệch").
test_case("chuejceh", "chuệch").
test_case("chuejche", "chuệch").
test_case("chuecejh", "chuệch").
test_case("chuecehj", "chuệch").
test_case("chuecjeh", "chuệch").
test_case("chueechj", "chuệch").
test_case("chueecjh", "chuệch").
test_case("chueejch", "chuệch").
test_case("chuejech", "chuệch").
test_case("chuechje", "chuệch").
test_case("bepes", "bếp").
test_case("beeps", "bếp").
test_case("besep", "bếp").
test_case("bepse", "bếp").
test_case("bespe", "bếp").
test_case("beesp", "bếp").
test_case("rejep", "rệp").
test_case("repje", "rệp").
test_case("rejpe", "rệp").
test_case("repej", "rệp").
test_case("reepj", "rệp").
test_case("reejp", "rệp").
test_case("bost", "bót").
test_case("bots", "bót").
test_case("bojt", "bọt").
test_case("botj", "bọt").
test_case("biene", "biên").
test_case("bieen", "biên").
test_case("bienes", "biến").
test_case("biesen", "biến").
test_case("biense", "biến").
test_case("bieesn", "biến").
test_case("bieens", "biến").
test_case("biesne", "biến").
test_case("bienfe", "biền").
test_case("bieenf", "biền").
test_case("biefne", "biền").
test_case("bienef", "biền").
test_case("bieefn", "biền").
test_case("biefen", "biền").
test_case("bieren", "biển").
test_case("biener", "biển").
test_case("bierne", "biển").
test_case("bieern", "biển").
test_case("bienre", "biển").
test_case("bieenr", "biển").
test_case("bienej", "biện").
test_case("bieenj", "biện").
test_case("biejne", "biện").
test_case("bienje", "biện").
test_case("bieejn", "biện").
test_case("biejen", "biện").
test_case("diexne", "diễn").
test_case("dieexn", "diễn").
test_case("diexen", "diễn").
test_case("dieenx", "diễn").
test_case("dienxe", "diễn").
test_case("dienex", "diễn").
test_case("bifnh", "bình").
test_case("binhf", "bình").
test_case("binfh", "bình").
test_case("binhs", "bính").
test_case("bisnh", "bính").
test_case("binsh", "bính").
test_case("binhx", "bĩnh").
test_case("bixnh", "bĩnh").
test_case("binxh", "bĩnh").
test_case("binhr", "bỉnh").
test_case("binrh", "bỉnh").
test_case("birnh", "bỉnh").
test_case("binhj", "bịnh").
test_case("bijnh", "bịnh").
test_case("binjh", "bịnh").
test_case("dindh", "đinh").
test_case("ddinh", "đinh").
test_case("didnh", "đinh").
test_case("dinhd", "đinh").
test_case("bafo", "bào").
test_case("baof", "bào").
test_case("baos", "báo").
test_case("baso", "báo").
test_case("baxo", "bão").
test_case("baox", "bão").
test_case("baoj", "bạo").
test_case("bajo", "bạo").
test_case("baor", "bảo").
test_case("baro", "bảo").
test_case("ddao", "đao").
test_case("dado", "đao").
test_case("daod", "đao").
test_case("bufn", "bùn").
test_case("bunf", "bùn").
test_case("buns", "bún").
test_case("busn", "bún").
test_case("bunr", "bủn").
test_case("burn", "bủn").
test_case("chunx", "chũn").
test_case("chuxn", "chũn").
test_case("lujn", "lụn").
test_case("lunj", "lụn").
test_case("dund", "đun").
test_case("ddun", "đun").
test_case("dudn", "đun").
test_case("bafnh", "bành").
test_case("banfh", "bành").
test_case("banhf", "bành").
test_case("basnh", "bánh").
test_case("bansh", "bánh").
test_case("banhs", "bánh").
test_case("bajnh", "bạnh").
test_case("banjh", "bạnh").
test_case("banhj", "bạnh").
test_case("banrh", "bảnh").
test_case("banhr", "bảnh").
test_case("barnh", "bảnh").
test_case("haxnh", "hãnh").
test_case("hanxh", "hãnh").
test_case("hanhx", "hãnh").
test_case("dadnh", "đanh").
test_case("dandh", "đanh").
test_case("danhd", "đanh").
test_case("ddanh", "đanh").
test_case("khoaof", "khoào").
test_case("khoafo", "khoào").
test_case("ngoaso", "ngoáo").
test_case("ngoaos", "ngoáo").
test_case("choetj", "choẹt").
test_case("choejt", "choẹt").
test_case("hoest", "hoét").
test_case("hoets", "hoét").
test_case("bafy", "bày").
test_case("bayf", "bày").
test_case("bayr", "bảy").
test_case("bary", "bảy").
test_case("chasy", "cháy").
test_case("chays", "cháy").
test_case("chayj", "chạy").
test_case("chajy", "chạy").
test_case("daxy", "dãy").
test_case("dayx", "dãy").
test_case("dday", "đay").
test_case("dayd", "đay").
test_case("dady", "đay").
test_case("bafn", "bàn").
test_case("banf", "bàn").
test_case("basn", "bán").
test_case("bans", "bán").
test_case("bajn", "bạn").
test_case("banj", "bạn").
test_case("barn", "bản").
test_case("banr", "bản").
test_case("gianx", "giãn").
test_case("giaxn", "giãn").
test_case("dand", "đan").
test_case("ddan", "đan").
test_case("dadn", "đan").
test_case("buts", "bút").
test_case("bust", "bút").
test_case("butj", "bụt").
test_case("bujt", "bụt").
test_case("buowu", "bươu").
% test_case("buwowu", "bươu").
% test_case("buwouw", "bươu").
test_case("buouw", "bươu").
% test_case("buwowus", "bướu").
% test_case("buwoswu", "bướu").
test_case("buoswu", "bướu").
% test_case("buwousw", "bướu").
% test_case("buwosuw", "bướu").
% test_case("buwouws", "bướu").
% test_case("buwowsu", "bướu").
test_case("buousw", "bướu").
test_case("buosuw", "bướu").
test_case("buowsu", "bướu").
test_case("buouws", "bướu").
test_case("buowus", "bướu").
test_case("phuojwu", "phượu").
% test_case("phuwojuw", "phượu").
test_case("phuouwj", "phượu").
% test_case("phuwouwj", "phượu").
% test_case("phuwojwu", "phượu").
% test_case("phuwowju", "phượu").
% test_case("phuwowuj", "phượu").
test_case("phuowju", "phượu").
test_case("phuoujw", "phượu").
% test_case("phuwoujw", "phượu").
test_case("phuojuw", "phượu").
test_case("phuowuj", "phượu").
% test_case("tuwoufw", "tườu").
% test_case("tuwowuf", "tườu").
test_case("tuouwf", "tườu").
test_case("tuofuw", "tườu").
% test_case("tuwofuw", "tườu").
test_case("tuowfu", "tườu").
test_case("tuowuf", "tườu").
% test_case("tuwouwf", "tườu").
% test_case("tuwofwu", "tườu").
test_case("tuofwu", "tườu").
% test_case("tuwowfu", "tườu").
test_case("tuoufw", "tườu").
test_case("baast", "bất").
test_case("batsa", "bất").
test_case("basta", "bất").
test_case("batas", "bất").
test_case("basat", "bất").
test_case("baats", "bất").
test_case("baajt", "bật").
test_case("batja", "bật").
test_case("bajta", "bật").
test_case("bataj", "bật").
test_case("bajat", "bật").
test_case("baatj", "bật").
test_case("basca", "bấc").
test_case("bacas", "bấc").
test_case("basac", "bấc").
test_case("bacsa", "bấc").
test_case("baacs", "bấc").
test_case("baasc", "bấc").
test_case("bacaj", "bậc").
test_case("bacja", "bậc").
test_case("bajac", "bậc").
test_case("baajc", "bậc").
test_case("bajca", "bậc").
test_case("baacj", "bậc").
test_case("bamw", "băm").
test_case("bawm", "băm").
test_case("bawfm", "bằm").
test_case("bamfw", "bằm").
test_case("bawmf", "bằm").
test_case("bafwm", "bằm").
test_case("bamwf", "bằm").
test_case("bafmw", "bằm").
test_case("bawjm", "bặm").
test_case("bawmj", "bặm").
test_case("bamjw", "bặm").
test_case("bajmw", "bặm").
test_case("bajwm", "bặm").
test_case("bamwj", "bặm").
test_case("chawms", "chắm").
test_case("chamsw", "chắm").
test_case("chasmw", "chắm").
test_case("chawsm", "chắm").
test_case("chamws", "chắm").
test_case("chaswm", "chắm").
test_case("khamwr", "khẳm").
test_case("khamrw", "khẳm").
test_case("khawrm", "khẳm").
test_case("kharwm", "khẳm").
test_case("kharmw", "khẳm").
test_case("khawmr", "khẳm").
test_case("dadwxm", "đẵm").
test_case("ddamxw", "đẵm").
test_case("ddawxm", "đẵm").
test_case("daxdmw", "đẵm").
test_case("ddamwx", "đẵm").
test_case("daxmwd", "đẵm").
test_case("dadwmx", "đẵm").
test_case("damwdx", "đẵm").
test_case("daxmdw", "đẵm").
test_case("damxdw", "đẵm").
test_case("damdxw", "đẵm").
test_case("ddawmx", "đẵm").
test_case("ddaxmw", "đẵm").
test_case("dawdmx", "đẵm").
test_case("dadmxw", "đẵm").
test_case("dadxmw", "đẵm").
test_case("dawmdx", "đẵm").
test_case("daxdwm", "đẵm").
test_case("ddaxwm", "đẵm").
test_case("damdwx", "đẵm").
test_case("dawxmd", "đẵm").
test_case("dawmxd", "đẵm").
test_case("damxwd", "đẵm").
test_case("dawxdm", "đẵm").
test_case("dadxwm", "đẵm").
test_case("daxwdm", "đẵm").
test_case("daxwmd", "đẵm").
test_case("damwxd", "đẵm").
test_case("dadmwx", "đẵm").
test_case("dawdxm", "đẵm").
test_case("bast", "bát").
test_case("bats", "bát").
test_case("bajt", "bạt").
test_case("batj", "bạt").
test_case("choawts", "choắt").
test_case("choatws", "choắt").
test_case("choastw", "choắt").
test_case("choatsw", "choắt").
test_case("choaswt", "choắt").
test_case("choawst", "choắt").
test_case("ngoajwt", "ngoặt").
test_case("ngoajtw", "ngoặt").
test_case("ngoawtj", "ngoặt").
test_case("ngoawjt", "ngoặt").
test_case("ngoatjw", "ngoặt").
test_case("ngoatwj", "ngoặt").
test_case("beneh", "bênh").
test_case("benhe", "bênh").
test_case("beenh", "bênh").
test_case("benfeh", "bềnh").
test_case("benhfe", "bềnh").
test_case("beenfh", "bềnh").
test_case("benfhe", "bềnh").
test_case("benehf", "bềnh").
test_case("benhef", "bềnh").
test_case("befenh", "bềnh").
test_case("benefh", "bềnh").
test_case("beenhf", "bềnh").
test_case("befneh", "bềnh").
test_case("befnhe", "bềnh").
test_case("beefnh", "bềnh").
test_case("benjeh", "bệnh").
test_case("benejh", "bệnh").
test_case("benhej", "bệnh").
test_case("beenhj", "bệnh").
test_case("benjhe", "bệnh").
test_case("benehj", "bệnh").
test_case("bejenh", "bệnh").
test_case("beejnh", "bệnh").
test_case("benhje", "bệnh").
test_case("bejnhe", "bệnh").
test_case("beenjh", "bệnh").
test_case("bejneh", "bệnh").
test_case("chenhes", "chếnh").
test_case("chesnhe", "chếnh").
test_case("cheensh", "chếnh").
test_case("chesenh", "chếnh").
test_case("chesneh", "chếnh").
test_case("chenseh", "chếnh").
test_case("cheesnh", "chếnh").
test_case("chenshe", "chếnh").
test_case("chenehs", "chếnh").
test_case("chenhse", "chếnh").
test_case("chenesh", "chếnh").
test_case("cheenhs", "chếnh").
test_case("cheernh", "chểnh").
test_case("cherneh", "chểnh").
test_case("chenreh", "chểnh").
test_case("chernhe", "chểnh").
test_case("cheenhr", "chểnh").
test_case("cheenrh", "chểnh").
test_case("chenehr", "chểnh").
test_case("chenrhe", "chểnh").
test_case("chenhre", "chểnh").
test_case("cherenh", "chểnh").
test_case("chenher", "chểnh").
test_case("chenerh", "chểnh").
test_case("chexenh", "chễnh").
test_case("chenxeh", "chễnh").
test_case("chenexh", "chễnh").
test_case("cheexnh", "chễnh").
test_case("chenehx", "chễnh").
test_case("chexneh", "chễnh").
test_case("cheenxh", "chễnh").
test_case("chenxhe", "chễnh").
test_case("chexnhe", "chễnh").
test_case("cheenhx", "chễnh").
test_case("chenhxe", "chễnh").
test_case("chenhex", "chễnh").
test_case("quynsh", "quýnh").
test_case("quynhs", "quýnh").
test_case("quysnh", "quýnh").
test_case("quynfh", "quỳnh").
test_case("quynhf", "quỳnh").
test_case("quyfnh", "quỳnh").
test_case("quynhr", "quỷnh").
test_case("quynrh", "quỷnh").
test_case("quyrnh", "quỷnh").
test_case("cheme", "chêm").
test_case("cheem", "chêm").
test_case("chefme", "chềm").
test_case("cheemf", "chềm").
test_case("chefem", "chềm").
test_case("chemfe", "chềm").
test_case("chemef", "chềm").
test_case("cheefm", "chềm").
test_case("chexme", "chễm").
test_case("chexem", "chễm").
test_case("cheexm", "chễm").
test_case("chemex", "chễm").
test_case("chemxe", "chễm").
test_case("cheemx", "chễm").
test_case("giesme", "giếm").
test_case("gieems", "giếm").
test_case("gieesm", "giếm").
test_case("giesem", "giếm").
test_case("giemes", "giếm").
test_case("giemse", "giếm").
test_case("neejm", "nệm").
test_case("nemej", "nệm").
test_case("nejme", "nệm").
test_case("neemj", "nệm").
test_case("nejem", "nệm").
test_case("nemje", "nệm").
test_case("huycsh", "huých").
test_case("huychs", "huých").
test_case("huysch", "huých").
test_case("huyjch", "huỵch").
test_case("huycjh", "huỵch").
test_case("huychj", "huỵch").
test_case("doanhf", "doành").
test_case("doanfh", "doành").
test_case("doafnh", "doành").
test_case("hoanjh", "hoạnh").
test_case("hoajnh", "hoạnh").
test_case("hoanhj", "hoạnh").
test_case("hoanrh", "hoảnh").
test_case("hoarnh", "hoảnh").
test_case("hoanhr", "hoảnh").
% test_case("buwowi", "bươi").
% test_case("buwoiw", "bươi").
test_case("buowi", "bươi").
test_case("buoiw", "bươi").
% test_case("buworwi", "bưởi").
test_case("buoiwr", "bưởi").
% test_case("buwowri", "bưởi").
% test_case("buwoiwr", "bưởi").
test_case("buoirw", "bưởi").
% test_case("buworiw", "bưởi").
test_case("buorwi", "bưởi").
% test_case("buwowir", "bưởi").
% test_case("buwoirw", "bưởi").
test_case("buowri", "bưởi").
test_case("buowir", "bưởi").
test_case("buoriw", "bưởi").
test_case("cuoswi", "cưới").
test_case("cuosiw", "cưới").
% test_case("cuwoiws", "cưới").
% test_case("cuwowsi", "cưới").
% test_case("cuwowis", "cưới").
% test_case("cuwosiw", "cưới").
test_case("cuoisw", "cưới").
% test_case("cuwoisw", "cưới").
test_case("cuowis", "cưới").
test_case("cuoiws", "cưới").
test_case("cuowsi", "cưới").
% test_case("cuwoswi", "cưới").
% test_case("cuwowfi", "cười").
% test_case("cuwowif", "cười").
test_case("cuofiw", "cười").
% test_case("cuwoifw", "cười").
% test_case("cuwofiw", "cười").
test_case("cuoifw", "cười").
test_case("cuowfi", "cười").
% test_case("cuwofwi", "cười").
test_case("cuowif", "cười").
test_case("cuofwi", "cười").
% test_case("cuwoiwf", "cười").
test_case("cuoiwf", "cười").
test_case("cuoxiw", "cưỡi").
test_case("cuoiwx", "cưỡi").
% test_case("cuwowxi", "cưỡi").
test_case("cuowix", "cưỡi").
% test_case("cuwoxiw", "cưỡi").
% test_case("cuwowix", "cưỡi").
test_case("cuoixw", "cưỡi").
% test_case("cuwoxwi", "cưỡi").
% test_case("cuwoixw", "cưỡi").
% test_case("cuwoiwx", "cưỡi").
test_case("cuoxwi", "cưỡi").
test_case("cuowxi", "cưỡi").
test_case("ruowji", "rượi").
test_case("ruowij", "rượi").
test_case("ruojwi", "rượi").
% test_case("ruwowji", "rượi").
% test_case("ruwoiwj", "rượi").
test_case("ruoiwj", "rượi").
% test_case("ruwojwi", "rượi").
% test_case("ruwojiw", "rượi").
% test_case("ruwowij", "rượi").
% test_case("ruwoijw", "rượi").
test_case("ruoijw", "rượi").
test_case("ruojiw", "rượi").
% test_case("buwown", "bươn").
test_case("buonw", "bươn").
test_case("buown", "bươn").
% test_case("buwonw", "bươn").
test_case("luownf", "lườn").
% test_case("luwowfn", "lườn").
test_case("luofnw", "lườn").
% test_case("luwofwn", "lườn").
% test_case("luwofnw", "lườn").
% test_case("luwonwf", "lườn").
test_case("luowfn", "lườn").
% test_case("luwonfw", "lườn").
test_case("luonfw", "lườn").
test_case("luonwf", "lườn").
test_case("luofwn", "lườn").
% test_case("luwownf", "lườn").
test_case("luojwn", "lượn").
% test_case("luwonjw", "lượn").
% test_case("luwonwj", "lượn").
test_case("luownj", "lượn").
% test_case("luwownj", "lượn").
% test_case("luwojwn", "lượn").
test_case("luonjw", "lượn").
test_case("luojnw", "lượn").
% test_case("luwojnw", "lượn").
test_case("luowjn", "lượn").
test_case("luonwj", "lượn").
% test_case("luwowjn", "lượn").
test_case("muoswn", "mướn").
% test_case("muwonsw", "mướn").
test_case("muonws", "mướn").
test_case("muowsn", "mướn").
% test_case("muwoswn", "mướn").
% test_case("muwowns", "mướn").
test_case("muosnw", "mướn").
% test_case("muwosnw", "mướn").
test_case("muowns", "mướn").
% test_case("muwonws", "mướn").
test_case("muonsw", "mướn").
% test_case("muwowsn", "mướn").
% test_case("phuwonwx", "phưỡn").
test_case("phuoxnw", "phưỡn").
test_case("phuownx", "phưỡn").
test_case("phuonwx", "phưỡn").
% test_case("phuwownx", "phưỡn").
test_case("phuoxwn", "phưỡn").
% test_case("phuwoxnw", "phưỡn").
% test_case("phuwonxw", "phưỡn").
test_case("phuowxn", "phưỡn").
% test_case("phuwowxn", "phưỡn").
% test_case("phuwoxwn", "phưỡn").
test_case("phuonxw", "phưỡn").
test_case("buwu", "bưu").
test_case("buuw", "bưu").
test_case("buuwr", "bửu").
test_case("buwur", "bửu").
test_case("buwru", "bửu").
test_case("buurw", "bửu").
test_case("burwu", "bửu").
test_case("buruw", "bửu").
test_case("cuswu", "cứu").
test_case("cuuws", "cứu").
test_case("cuusw", "cứu").
test_case("cuwsu", "cứu").
test_case("cusuw", "cứu").
test_case("cuwus", "cứu").
test_case("cufwu", "cừu").
test_case("cuwfu", "cừu").
test_case("cufuw", "cừu").
test_case("cuuwf", "cừu").
test_case("cuufw", "cừu").
test_case("cuwuf", "cừu").
test_case("cuxuw", "cữu").
test_case("cuxwu", "cữu").
test_case("cuwxu", "cữu").
test_case("cuwux", "cữu").
test_case("cuuwx", "cữu").
test_case("cuuxw", "cữu").
test_case("cuujw", "cựu").
test_case("cujwu", "cựu").
test_case("cujuw", "cựu").
test_case("cuwuj", "cựu").
test_case("cuwju", "cựu").
test_case("cuuwj", "cựu").
test_case("bown", "bơn").
test_case("bonw", "bơn").
test_case("bonwf", "bờn").
test_case("bowfn", "bờn").
test_case("bownf", "bờn").
test_case("bofwn", "bờn").
test_case("bonfw", "bờn").
test_case("bofnw", "bờn").
test_case("boxnw", "bỡn").
test_case("bonwx", "bỡn").
test_case("bownx", "bỡn").
test_case("bonxw", "bỡn").
test_case("bowxn", "bỡn").
test_case("boxwn", "bỡn").
test_case("bonjw", "bợn").
test_case("bowjn", "bợn").
test_case("bojwn", "bợn").
test_case("bojnw", "bợn").
test_case("bownj", "bợn").
test_case("bonwj", "bợn").
test_case("conws", "cớn").
test_case("consw", "cớn").
test_case("cowsn", "cớn").
test_case("cowns", "cớn").
test_case("coswn", "cớn").
test_case("cosnw", "cớn").
test_case("lowrn", "lởn").
test_case("lownr", "lởn").
test_case("lonrw", "lởn").
test_case("lorwn", "lởn").
test_case("lonwr", "lởn").
test_case("lornw", "lởn").
test_case("quyeest", "quyết").
test_case("quyeset", "quyết").
test_case("quyeets", "quyết").
test_case("quyetes", "quyết").
test_case("quyeste", "quyết").
test_case("quyetse", "quyết").
test_case("quyetje", "quyệt").
test_case("quyeetj", "quyệt").
test_case("quyeejt", "quyệt").
test_case("quyetej", "quyệt").
test_case("quyejte", "quyệt").
test_case("quyejet", "quyệt").
test_case("bacs", "bác").
test_case("basc", "bác").
test_case("bacj", "bạc").
test_case("bajc", "bạc").
test_case("buotwj", "bượt").
test_case("buotjw", "bượt").
% test_case("buwojwt", "bượt").
% test_case("buwojtw", "bượt").
test_case("buojtw", "bượt").
% test_case("buwowtj", "bượt").
% test_case("buwowjt", "bượt").
% test_case("buwotjw", "bượt").
% test_case("buwotwj", "bượt").
test_case("buowjt", "bượt").
test_case("buowtj", "bượt").
test_case("buojwt", "bượt").
test_case("khuostw", "khướt").
% test_case("khuwotsw", "khướt").
% test_case("khuwoswt", "khướt").
test_case("khuotsw", "khướt").
test_case("khuowts", "khướt").
test_case("khuoswt", "khướt").
% test_case("khuwotws", "khướt").
test_case("khuowst", "khướt").
test_case("khuotws", "khướt").
% test_case("khuwowts", "khướt").
% test_case("khuwostw", "khướt").
% test_case("khuwowst", "khướt").
test_case("yeneg", "yêng").
test_case("yeeng", "yêng").
test_case("yenge", "yêng").
test_case("yenreg", "yểng").
test_case("yeerng", "yểng").
test_case("yeenrg", "yểng").
test_case("yengre", "yểng").
test_case("yenerg", "yểng").
test_case("yenger", "yểng").
test_case("yenegr", "yểng").
test_case("yerneg", "yểng").
test_case("yereng", "yểng").
test_case("yeengr", "yểng").
test_case("yernge", "yểng").
test_case("yenrge", "yểng").
test_case("huow", "huơ").
test_case("thuowr", "thuở").
test_case("thuorw", "thuở").
test_case("baua", "bâu").
test_case("baau", "bâu").
test_case("basau", "bấu").
test_case("basua", "bấu").
test_case("baasu", "bấu").
test_case("bausa", "bấu").
test_case("bauas", "bấu").
test_case("baaus", "bấu").
test_case("bafua", "bầu").
test_case("baafu", "bầu").
test_case("bafau", "bầu").
test_case("bauaf", "bầu").
test_case("baufa", "bầu").
test_case("baauf", "bầu").
test_case("bajua", "bậu").
test_case("baauj", "bậu").
test_case("bajau", "bậu").
test_case("bauja", "bậu").
test_case("bauaj", "bậu").
test_case("baaju", "bậu").
test_case("chauxa", "chẫu").
test_case("chaxua", "chẫu").
test_case("chaaux", "chẫu").
test_case("chauax", "chẫu").
test_case("chaaxu", "chẫu").
test_case("chaxau", "chẫu").
test_case("carau", "cẩu").
test_case("caura", "cẩu").
test_case("cauar", "cẩu").
test_case("caaru", "cẩu").
test_case("caaur", "cẩu").
test_case("carua", "cẩu").
test_case("humwf", "hừm").
test_case("hufmw", "hừm").
test_case("hufwm", "hừm").
test_case("huwmf", "hừm").
test_case("humfw", "hừm").
test_case("huwfm", "hừm").
test_case("booonsg", "boóng").
test_case("booosng", "boóng").
test_case("booongs", "boóng").
test_case("chooongf", "choòng").
test_case("chooonfg", "choòng").
test_case("chooofng", "choòng").
test_case("baif", "bài").
test_case("bafi", "bài").
test_case("basi", "bái").
test_case("bais", "bái").
test_case("baxi", "bãi").
test_case("baix", "bãi").
test_case("baij", "bại").
test_case("baji", "bại").
test_case("bair", "bải").
test_case("bari", "bải").
test_case("dadi", "đai").
test_case("ddai", "đai").
test_case("daid", "đai").
test_case("bomf", "bòm").
test_case("bofm", "bòm").
test_case("boxm", "bõm").
test_case("bomx", "bõm").
test_case("borm", "bỏm").
test_case("bomr", "bỏm").
test_case("cojm", "cọm").
test_case("comj", "cọm").
test_case("dosm", "dóm").
test_case("doms", "dóm").
test_case("domd", "đom").
test_case("ddom", "đom").
test_case("dodm", "đom").
test_case("bucws", "bức").
test_case("buwsc", "bức").
test_case("buswc", "bức").
test_case("bucsw", "bức").
test_case("buwcs", "bức").
test_case("buscw", "bức").
test_case("buwjc", "bực").
test_case("bucjw", "bực").
test_case("bujwc", "bực").
test_case("buwcj", "bực").
test_case("bujcw", "bực").
test_case("bucwj", "bực").
test_case("butsw", "bứt").
test_case("buwts", "bứt").
test_case("bustw", "bứt").
test_case("buswt", "bứt").
test_case("buwst", "bứt").
test_case("butws", "bứt").
test_case("buwtj", "bựt").
test_case("butjw", "bựt").
test_case("bujwt", "bựt").
test_case("buwjt", "bựt").
test_case("butwj", "bựt").
test_case("bujtw", "bựt").
test_case("bospo", "bốp").
test_case("boosp", "bốp").
test_case("bosop", "bốp").
test_case("bopso", "bốp").
test_case("boops", "bốp").
test_case("bopos", "bốp").
test_case("boojp", "bộp").
test_case("bojpo", "bộp").
test_case("boopj", "bộp").
test_case("bopoj", "bộp").
test_case("bojop", "bộp").
test_case("bopjo", "bộp").
test_case("hoacws", "hoắc").
test_case("hoacsw", "hoắc").
test_case("hoawsc", "hoắc").
test_case("hoaswc", "hoắc").
test_case("hoawcs", "hoắc").
test_case("hoascw", "hoắc").
test_case("hoawcj", "hoặc").
test_case("hoacwj", "hoặc").
test_case("hoacjw", "hoặc").
test_case("hoajcw", "hoặc").
test_case("hoawjc", "hoặc").
test_case("hoajwc", "hoặc").
test_case("beeu", "bêu").
test_case("beue", "bêu").
test_case("befeu", "bều").
test_case("beeuf", "bều").
test_case("beefu", "bều").
test_case("befue", "bều").
test_case("beufe", "bều").
test_case("beuef", "bều").
test_case("beuej", "bệu").
test_case("beuje", "bệu").
test_case("bejeu", "bệu").
test_case("bejue", "bệu").
test_case("beeuj", "bệu").
test_case("beeju", "bệu").
test_case("gieuxe", "giễu").
test_case("giexue", "giễu").
test_case("gieexu", "giễu").
test_case("gieuex", "giễu").
test_case("gieeux", "giễu").
test_case("giexeu", "giễu").
test_case("heues", "hếu").
test_case("heuse", "hếu").
test_case("heesu", "hếu").
test_case("hesue", "hếu").
test_case("heeus", "hếu").
test_case("heseu", "hếu").
test_case("leuer", "lểu").
test_case("leeru", "lểu").
test_case("lereu", "lểu").
test_case("leure", "lểu").
test_case("lerue", "lểu").
test_case("leeur", "lểu").
test_case("bonf", "bòn").
test_case("bofn", "bòn").
test_case("bosn", "bón").
test_case("bons", "bón").
test_case("bonj", "bọn").
test_case("bojn", "bọn").
test_case("chonr", "chỏn").
test_case("chorn", "chỏn").
test_case("nhoxn", "nhõn").
test_case("nhonx", "nhõn").
test_case("ddon", "đon").
test_case("dodn", "đon").
test_case("dond", "đon").
test_case("baf", "bà").
test_case("bas", "bá").
test_case("bax", "bã").
test_case("baj", "bạ").
test_case("bar", "bả").
test_case("dda", "đa").
test_case("dad", "đa").
test_case("buyts", "buýt").
test_case("buyst", "buýt").
test_case("suyjt", "suỵt").
test_case("suytj", "suỵt").
test_case("bowi", "bơi").
test_case("boiw", "bơi").
test_case("bosiw", "bới").
test_case("bowis", "bới").
test_case("boiws", "bới").
test_case("boisw", "bới").
test_case("boswi", "bới").
test_case("bowsi", "bới").
test_case("boifw", "bời").
test_case("boiwf", "bời").
test_case("bowif", "bời").
test_case("bofwi", "bời").
test_case("bowfi", "bời").
test_case("bofiw", "bời").
test_case("bowir", "bởi").
test_case("boirw", "bởi").
test_case("bowri", "bởi").
test_case("boiwr", "bởi").
test_case("borwi", "bởi").
test_case("boriw", "bởi").
test_case("coxiw", "cỡi").
test_case("coxwi", "cỡi").
test_case("coixw", "cỡi").
test_case("cowxi", "cỡi").
test_case("cowix", "cỡi").
test_case("coiwx", "cỡi").
test_case("gowji", "gợi").
test_case("gojwi", "gợi").
test_case("goijw", "gợi").
test_case("gojiw", "gợi").
test_case("goiwj", "gợi").
test_case("gowij", "gợi").
test_case("dueenhf", "duềnh").
test_case("duenefh", "duềnh").
test_case("duenehf", "duềnh").
test_case("duenhfe", "duềnh").
test_case("dueenfh", "duềnh").
test_case("duefnhe", "duềnh").
test_case("dueefnh", "duềnh").
test_case("duefneh", "duềnh").
test_case("duenfeh", "duềnh").
test_case("duenhef", "duềnh").
test_case("duefenh", "duềnh").
test_case("duenfhe", "duềnh").
test_case("hueenh", "huênh").
test_case("hueneh", "huênh").
test_case("huenhe", "huênh").
test_case("best", "bét").
test_case("bets", "bét").
test_case("bejt", "bẹt").
test_case("betj", "bẹt").
test_case("besc", "béc").
test_case("becs", "béc").
test_case("khejc", "khẹc").
test_case("khecj", "khẹc").
test_case("bafm", "bàm").
test_case("bamf", "bàm").
test_case("basm", "bám").
test_case("bams", "bám").
test_case("chamj", "chạm").
test_case("chajm", "chạm").
test_case("carm", "cảm").
test_case("camr", "cảm").
test_case("hamx", "hãm").
test_case("haxm", "hãm").
test_case("ddam", "đam").
test_case("dadm", "đam").
test_case("damd", "đam").
test_case("huynfh", "huỳnh").
test_case("huyfnh", "huỳnh").
test_case("huynhf", "huỳnh").
test_case("luynsh", "luýnh").
test_case("luynhs", "luýnh").
test_case("luysnh", "luýnh").
test_case("bif", "bì").
test_case("bis", "bí").
test_case("bix", "bĩ").
test_case("bir", "bỉ").
test_case("bij", "bị").
test_case("ddi", "đi").
test_case("did", "đi").
test_case("choangf", "choàng").
test_case("choafng", "choàng").
test_case("choanfg", "choàng").
test_case("choasng", "choáng").
test_case("choansg", "choáng").
test_case("choangs", "choáng").
test_case("choajng", "choạng").
test_case("choanjg", "choạng").
test_case("choangj", "choạng").
test_case("choangr", "choảng").
test_case("choarng", "choảng").
test_case("choanrg", "choảng").
test_case("doaxng", "doãng").
test_case("doangx", "doãng").
test_case("doanxg", "doãng").
test_case("giesce", "giếc").
test_case("gieecs", "giếc").
test_case("giesec", "giếc").
test_case("gieces", "giếc").
test_case("gieesc", "giếc").
test_case("giecse", "giếc").
test_case("bofng", "bòng").
test_case("bonfg", "bòng").
test_case("bongf", "bòng").
test_case("bosng", "bóng").
test_case("bongs", "bóng").
test_case("bonsg", "bóng").
test_case("bonxg", "bõng").
test_case("bongx", "bõng").
test_case("boxng", "bõng").
test_case("bojng", "bọng").
test_case("bonjg", "bọng").
test_case("bongj", "bọng").
test_case("bongr", "bỏng").
test_case("borng", "bỏng").
test_case("bonrg", "bỏng").
test_case("ddong", "đong").
test_case("dongd", "đong").
test_case("dondg", "đong").
test_case("dodng", "đong").
test_case("bits", "bít").
test_case("bist", "bít").
test_case("bitj", "bịt").
test_case("bijt", "bịt").
test_case("hoacjh", "hoạch").
test_case("hoajch", "hoạch").
test_case("hoachj", "hoạch").
test_case("ngoacsh", "ngoách").
test_case("ngoasch", "ngoách").
test_case("ngoachs", "ngoách").
test_case("bunfg", "bùng").
test_case("bungf", "bùng").
test_case("bufng", "bùng").
test_case("bungs", "búng").
test_case("busng", "búng").
test_case("bunsg", "búng").
test_case("bujng", "bụng").
test_case("bunjg", "bụng").
test_case("bungj", "bụng").
test_case("burng", "bủng").
test_case("bungr", "bủng").
test_case("bunrg", "bủng").
test_case("cuxng", "cũng").
test_case("cunxg", "cũng").
test_case("cungx", "cũng").
test_case("dundg", "đung").
test_case("dungd", "đung").
test_case("ddung", "đung").
test_case("dudng", "đung").
test_case("bajp", "bạp").
test_case("bapj", "bạp").
test_case("caps", "cáp").
test_case("casp", "cáp").
test_case("betes", "bết").
test_case("beset", "bết").
test_case("beest", "bết").
test_case("betse", "bết").
test_case("beste", "bết").
test_case("beets", "bết").
test_case("bejet", "bệt").
test_case("betej", "bệt").
test_case("bejte", "bệt").
test_case("beejt", "bệt").
test_case("betje", "bệt").
test_case("beetj", "bệt").
test_case("teet", "têt").
test_case("tete", "têt").
test_case("bow", "bơ").
test_case("bows", "bớ").
test_case("bosw", "bớ").
test_case("bowf", "bờ").
test_case("bofw", "bờ").
test_case("borw", "bở").
test_case("bowr", "bở").
test_case("bowx", "bỡ").
test_case("boxw", "bỡ").
test_case("bojw", "bợ").
test_case("bowj", "bợ").
test_case("bufm", "bùm").
test_case("bumf", "bùm").
test_case("buxm", "bũm").
test_case("bumx", "bũm").
test_case("bumj", "bụm").
test_case("bujm", "bụm").
test_case("burm", "bủm").
test_case("bumr", "bủm").
test_case("chusm", "chúm").
test_case("chums", "chúm").
test_case("ddum", "đum").
test_case("dudm", "đum").
test_case("dumd", "đum").
test_case("bifa", "bìa").
test_case("biaf", "bìa").
test_case("bija", "bịa").
test_case("biaj", "bịa").
test_case("chixa", "chĩa").
test_case("chiax", "chĩa").
test_case("khias", "khía").
test_case("khisa", "khía").
test_case("mira", "mỉa").
test_case("miar", "mỉa").
test_case("baan", "bân").
test_case("bana", "bân").
test_case("banas", "bấn").
test_case("basan", "bấn").
test_case("bansa", "bấn").
test_case("baasn", "bấn").
test_case("baans", "bấn").
test_case("basna", "bấn").
test_case("bafan", "bần").
test_case("bafna", "bần").
test_case("banfa", "bần").
test_case("baafn", "bần").
test_case("baanf", "bần").
test_case("banaf", "bần").
test_case("baran", "bẩn").
test_case("barna", "bẩn").
test_case("banra", "bẩn").
test_case("baarn", "bẩn").
test_case("baanr", "bẩn").
test_case("banar", "bẩn").
test_case("bajna", "bận").
test_case("banaj", "bận").
test_case("bajan", "bận").
test_case("baanj", "bận").
test_case("banja", "bận").
test_case("baajn", "bận").
test_case("caanx", "cẫn").
test_case("caaxn", "cẫn").
test_case("canxa", "cẫn").
test_case("caxna", "cẫn").
test_case("canax", "cẫn").
test_case("caxan", "cẫn").
test_case("bichs", "bích").
test_case("bicsh", "bích").
test_case("bisch", "bích").
test_case("bijch", "bịch").
test_case("bicjh", "bịch").
test_case("bichj", "bịch").
test_case("buoon", "buôn").
test_case("buono", "buôn").
test_case("buonof", "buồn").
test_case("buonfo", "buồn").
test_case("buoofn", "buồn").
test_case("buoonf", "buồn").
test_case("buofno", "buồn").
test_case("buofon", "buồn").
test_case("cuoson", "cuốn").
test_case("cuonso", "cuốn").
test_case("cuoosn", "cuốn").
test_case("cuosno", "cuốn").
test_case("cuonos", "cuốn").
test_case("cuoons", "cuốn").
test_case("cuonoj", "cuộn").
test_case("cuoojn", "cuộn").
test_case("cuojon", "cuộn").
test_case("cuojno", "cuộn").
test_case("cuoonj", "cuộn").
test_case("cuonjo", "cuộn").
test_case("thuonxo", "thuỗn").
test_case("thuoonx", "thuỗn").
test_case("thuoxon", "thuỗn").
test_case("thuoxno", "thuỗn").
test_case("thuooxn", "thuỗn").
test_case("thuonox", "thuỗn").
test_case("bowps", "bớp").
test_case("bopsw", "bớp").
test_case("boswp", "bớp").
test_case("bowsp", "bớp").
test_case("bopws", "bớp").
test_case("bospw", "bớp").
test_case("bopwj", "bợp").
test_case("bojpw", "bợp").
test_case("bojwp", "bợp").
test_case("bowjp", "bợp").
test_case("bowpj", "bợp").
test_case("bopjw", "bợp").
test_case("buopws", "bướp").
% test_case("buwopws", "bướp").
test_case("buospw", "bướp").
test_case("buoswp", "bướp").
test_case("buopsw", "bướp").
% test_case("buwoswp", "bướp").
% test_case("buwospw", "bướp").
test_case("buowps", "bướp").
% test_case("buwowsp", "bướp").
test_case("buowsp", "bướp").
% test_case("buwopsw", "bướp").
% test_case("buwowps", "bướp").
% test_case("chuwopjw", "chượp").
test_case("chuopwj", "chượp").
test_case("chuopjw", "chượp").
% test_case("chuwojpw", "chượp").
test_case("chuowjp", "chượp").
% test_case("chuwowjp", "chượp").
test_case("chuowpj", "chượp").
% test_case("chuwojwp", "chượp").
% test_case("chuwopwj", "chượp").
test_case("chuojwp", "chượp").
% test_case("chuwowpj", "chượp").
test_case("chuojpw", "chượp").
test_case("bufa", "bùa").
test_case("buaf", "bùa").
test_case("busa", "búa").
test_case("buas", "búa").
test_case("buaj", "bụa").
test_case("buja", "bụa").
test_case("buar", "bủa").
test_case("bura", "bủa").
test_case("giuxa", "giũa").
test_case("giuax", "giũa").
test_case("ddua", "đua").
test_case("duda", "đua").
test_case("duad", "đua").
test_case("chunw", "chưn").
test_case("chuwn", "chưn").
test_case("sunwf", "sừn").
test_case("sufwn", "sừn").
test_case("sufnw", "sừn").
test_case("sunfw", "sừn").
test_case("suwnf", "sừn").
test_case("suwfn", "sừn").
test_case("befm", "bèm").
test_case("bemf", "bèm").
test_case("bemr", "bẻm").
test_case("berm", "bẻm").
test_case("chesm", "chém").
test_case("chems", "chém").
test_case("hejm", "hẹm").
test_case("hemj", "hẹm").
test_case("kexm", "kẽm").
test_case("kemx", "kẽm").
test_case("dedm", "đem").
test_case("demd", "đem").
test_case("ddem", "đem").
test_case("beechj", "bệch").
test_case("becehj", "bệch").
test_case("bejche", "bệch").
test_case("bejceh", "bệch").
test_case("beejch", "bệch").
test_case("bechej", "bệch").
test_case("becjeh", "bệch").
test_case("bejech", "bệch").
test_case("bechje", "bệch").
test_case("becjhe", "bệch").
test_case("becejh", "bệch").
test_case("beecjh", "bệch").
test_case("cheecsh", "chếch").
test_case("checshe", "chếch").
test_case("cheechs", "chếch").
test_case("checesh", "chếch").
test_case("chechse", "chếch").
test_case("chesceh", "chếch").
test_case("cheches", "chếch").
test_case("chesche", "chếch").
test_case("checseh", "chếch").
test_case("chesech", "chếch").
test_case("checehs", "chếch").
test_case("cheesch", "chếch").
test_case("bapws", "bắp").
test_case("baswp", "bắp").
test_case("baspw", "bắp").
test_case("bapsw", "bắp").
test_case("bawps", "bắp").
test_case("bawsp", "bắp").
test_case("bajpw", "bặp").
test_case("bajwp", "bặp").
test_case("bawpj", "bặp").
test_case("bawjp", "bặp").
test_case("bapjw", "bặp").
test_case("bapwj", "bặp").
test_case("bosc", "bóc").
test_case("bocs", "bóc").
test_case("bojc", "bọc").
test_case("bocj", "bọc").